### ISSUE TITLE
NIWC Testbed Update - Slide # 22 - Light descriptions with unknown lightCharacteristic

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#10]
**S-101PT5 Action 24** - Discuss paper S-101PT5-21

[S-101PT5_21_EN_NIWC Test Bed Report_S101PT5_V1.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5290033/S-101PT5_21_EN_NIWC.Test.Bed.Report_S101PT5_V1.pdf)

![image](https://user-images.githubusercontent.com/70189016/94633164-d9e52d00-030f-11eb-9166-912fce429430.png)

**Comment by DavidGrant-NIWC** [comment]
This issue is specific to **LightAirObstruction** and **LightFogDetector** - what should the light description be when _lightCharacteristic_ is not present?

- _lightCharacteristic_ is a simple attribute with multiplicity 1:1 encoded as part of the complex attributes _rhythmOfLight_ and _sectorCharacteristics_
- The multiplicity of _rhythmOfLight_ is 0:1 for the two subject features
- The multiplicity of _rhythmOfLight_ is 1:1 for **LightAllAround**
- The multiplicity of _sectorCharacteristics_ is 1:∞ for **LightSectored**

Therefore _lightCharacteristic_ is always available for **LightAllAround** and **LightSectored**, but may not be available (unknown) for **LightAirObstruction** and **LightFogDetector**.

Recommendation is that no light description is output for the two subject features when _rhythmOfLight_ is not present.

**Comment by alvarosanuy** [comment]
According to S-52, Fog detector Lights are displayed starting with '**Fog Det Lt**'. If LITCHR is not present or Unknown is irrelevant as the type of light is clearly identified anyways.
Different is the case of Air obstruction lights. They do not have a CATLIT text identifier allocated to them. If LITCHR is also missing or Unknown, the first entry of the text string to be displayed is usually the colour.
I think S-101 should follow S-52 as close as possible.

**Comment by DavidGrant-NIWC** [comment]
In S-52 PresLib 4.0.2 10.6.3 _Light Description Text Strings_, the table which maps _LITCHR_ to an output text string does not specify how an unknown _LITCHR_ should be handled. This ambiguity can result in different ECDIS systems producing different results:
- It may result in the light being portrayed as a "?"
- It may result in the entire description being removed
- It may result in just the abbreviation of the characteristic being removed

In S-101, the portrayal catalogue ensures a consistent presentation for all systems. What should the portrayal catalogue generate for the light description string when _lightCharacteristic_ is not present? We just need consensus from the group so that the portrayal catalogue can be updated as desired. Our assumption is that adding a row to the S-57 Light Characteristic mapping table with "unknown" in the first column and "" (blank) in the abbreviation column would provide the desired output.

> ![image](https://user-images.githubusercontent.com/62906211/95894015-82ef4700-0d56-11eb-83c3-f929d6b911ca.png)

> ![image](https://user-images.githubusercontent.com/62906211/95892622-c6e14c80-0d54-11eb-8cf3-fe277f52c5b4.png)

**Comment by rmalyankar** [comment]
Annex C C-14.10.4 also contains this table, updated for S-101, and adds that: "Values not listed in this table are not represented in the light description string." That implies option 3. Up to this subWG to decide which option is preferable.

**Comment by SylviaSpohn-BSH** [comment]
If there are no values they can't be displayed. Could lead to option 3 or 2. Can we get more examples?

**Comment by alvarosanuy** [comment]
Considering that, for these two S-101 features, **rythmOfLight** is not a mandatory attribute, we prefer option 3 (display the light description skipping the abbreviation of the **lightCharacteristic**). Although it may not be well documented in S-52 we believe it is how it has been implemented by the majority of OEMs (ECDIS).

**Comment by DavidGrant-NIWC** [comment]
Recommend close - PC implements as option 3.

**Comment by alvarosanuy** [comment]
Decision made and changes implemented as required.
