### ISSUE TITLE
Implement 2 preferred QoBD portrayal options identified by the UNHCCOM - S-101PT9_2022_08.4 

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#113]
At S101PT9 meeting it was agreed to prototype (in branches of the PC 1.1.0) the 2 top preferred options for the depiction of **QoBD** identified by the research study conducted by the University of New Hampshire Center for Coastal and Ocean Mapping (UNHCCOM).

![image](https://user-images.githubusercontent.com/70189016/204970441-6193847c-8a74-416f-963a-d1d10410ae8a.png)
![image](https://user-images.githubusercontent.com/70189016/204970571-8e2263fe-cb0c-45e2-884f-3f8e234afd69.png)

Accordingly, the following actions are proposed:

1. Alvaro to liaise with Christos Kastrisios at UNHCCOM to send all technical instructions to NIWC (line width, colour, etc).
2. NIWC to amend existing QoBD rule to accommodate the 2 preferred visualization options identified by UNHCCOM in unique PC 1.1.0 versions.
3. S101PT Chair & Vice Chair to prepare and submit a task proposal to the IHO Secretariat requesting the use of special funds or by engaging the Singapore lab to thoroughly test the different options on an S100 ECDIS, by mariners in a simulator and at sea. The outcome of the project would be a thorough report on the pros & cons of the 2 options, lessons learnt and recommendations.

**Comment by MikusRL** [comment]
If I may, before the final submission, I propose to have a discussion within this Group, taking our main task as an additional variable to consider for the symbolization testing decision - the consideration of existing S-52 symbols. 

And I could start with my additional thoughts regarding the proposed symbolization. We briefly discussed with Christos during the meeting already, and that is that QoBD 1 as the best quality could be without any symbolization, which then accordingly would push the rest of symbolization one row down, giving benefit in the de-cluterization of the ECDIS work screen, when enabled. And this could definitely work in pure S-100 data situation. Even more, this could lead to it's permanent use as always ON, as then you would not have to worry about, when a worse quality data suddenly appears on screen, and navigator would not need to switch between on and of as frequently as today, or not at all. And only additional consideration could be a legend on ECDIS frame somewhere stating that the QoBD indicator (symbolization) is switched on - that to ensure the mariner he has it on. 

But what I would like to bring up to discussion for this Group here as a higher priority, before or while it goes to the Singapore Lab, is the compatibility consideration while the ECDIS would be in the dual fuel mode, the QoBD/CATZOC symbolization enabled, and with S-57 data on screen as well. In that regard my thought is that proposed "Lines" should have a higher priority in further investigation than the "Dot Clusters", simply because they are completely different symbol to existing CATZOC symbols, in some way, and still intuitive to see them side by side and be readable and correctly "comparable" and associate with the right quality value. Versus the "DotClusters", although the dots in the cluster comprises slightly differently, still could have a potential reading conflict for the end user - as when side by side the dots in the new symbol, and the stars in the old symbol will have different count. That makes it less reading friendly in the compatibility mode. Especially the fact could be not straight forward to remember - three stars are equal to three dots, but two stars are equal to four dots, etc. That makes it potentially to confuse in remembering the logic of compatibility, which potentially complicates its learning and use for about a decade or more. 
Even further, I would suggest, if moved further in investigation for potential use, the "Dots Cluster" symbol could be considered to align (harmonize the logic), to match the existing S-57 star symbolization and count, but still as proposed - new symbolization would not have the lines around the individual dot constellations. 

Also briefly discussed with Christos was a necessity to consider appropriate "border" line symbol, especially important with smaller QoBd areas encoded. In these the "Lines" symbolization could be not easy to read. And this consideration comes from the fact, that it is very likely that an HO can capture relatively small patches of QoBD, as capturing and encoding policies through different HOs vary greatly. Therefore the symbolization must be prepared to be able to portray it to the mariner.

**Comment by TomRichardson6** [comment]
@alvarosanuy I note action 3 and support it, I will discuss with the IHO Secretariat when I attend DQWG in February. 

One more fundamental question related to action 2- rather than use branches to support efficient testing could we not use a context parameter "DQ Display Option" and include these options in addition to the existing S-52 presentation within one Portrayal Catalogue?  Obviously this would be removed in later S-101 versions.

In practice I think this would enable easier testing otherwise separate Portrayal Catalogues would need to be configured.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 10/5/23**

- [x] **NIWC** to follow up with Christos to obtain the SVG files (and any other relevant info) required to implement the different QoBD area pattern options within the S101 PC.
- [ ] **NIWC** to temporarily implement a new context parameter ('DQ Display Option' ?) to facilitate the testing, in ECDIS, of the 2 new proposed options against the existing QoBD portrayal.
- [ ] **S101PT Chair & Vice Chair** to prepare and submit a proposal to the IHO Secretariat requesting the use of special funds or the Singapore lab to thoroughly test the different QoBD options in an S100 ECDIS, by mariners in a simulator and at sea. The outcome of the project would be a thorough report on the pros & cons of the 2 options, lessons learnt and recommendations.

**Comment by christoskas** [comment]
Mikus,
I understand your concerns about the dot-clusters and its similarity (and contradiction) to the current star symbology. However, I am confident that once mariners become familiar with the QoBD categories and the concept of the countable textures, it is very straightforward with both the dots and lines. Our survey and, particularly, the experiment showed that participants (professional mariners, cartographers, and hydrographers) had no difficulties in identifying the correct QoBD with the dot-clusters. On the contrary, in terms of corresponding symbol to QoBD level, the dot-clusters resulted in the least number of errors among all 5 coding schemes. My opinion is that we can make both available and allow users to select their symbology of preference. 

In terms of having quality 1 without symbolization, I believe we should allow users to make their own selection, i.e., all QoBD with symbology or selected without symbolization (e.g., quality 1 and 2) (using radio buttons). In the planning phase, when assessing safety of plotted route (or when straying from the initially plotted route, e.g, for ship handling), I would prefer to be able to see the symbology for all QoBD levels. In the execution/monitoring phase it would be great if I could de-activate certain levels so that I become aware when approaching areas of lower-quality data while reducing the visual weight in the areas of good quality data. If I had that flexibility, I would most likely keep the symbology permanently ON (as you wrote) for the selected QoBD levels. However, I wouldn't recommend pushing down the symbology one row down as the intuitiveness of the countable textures relies on this link between QoBD level and number of dots or lines, i.e., 1 dot for QoBD, 2 for 2 and so on.

**Comment by alvarosanuy** [comment]
@TomRichardson6 - It is recommended that a proposal to Singapore Lab to test the new QoBD symbology also includes a requirement to asses the value of implementing ECDIS performance changes as proposed in https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/73. In short, using a Marine selected 'safe ZOC' value to influence the visualization and triggering of A&I in ECDIS.

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/95b22231-4a78-4ff5-a145-c876bc264d15)

These actions are ongoing, there is a new branch in the S-101 PC to prototype the implementation (catzoc-alternate-portrayls): 
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/61fca5ae-3c6c-48f6-b591-cfd19bc21b18)

The branch currently allows selection between "classic" diamond symbology or "dots" via a new context parameter "QoBD Appearance".
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/6a00314b-425d-4630-be38-dcc4eebe9208)

Work remaining:
* Add support for night palette to dot symbology
* Add other symbolizations identified above?

**Comment by alvarosanuy** [comment]
> * **S101PT Chair & Vice Chair** to prepare and submit a proposal to the IHO Secretariat requesting the use of special funds or the Singapore lab to thoroughly test the different QoBD options in an S100 ECDIS, by mariners in a simulator and at sea. The outcome of the project would be a thorough report on the pros & cons of the 2 options, lessons learnt and recommendations

@TomRichardson6 - I remember some back and forth between the 2 of us on this drafting. Can you please summarise where is this request up to? I understand UNHCCOM's symbology was not available in the right format as to include it in an S-101PC version back then but we are really close now.
Furthermore, I believe we should use the opportunity (happy to update the latest draft proposal) and include a requirement to asses the value of implementing ECDIS performance changes as proposed in https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/73. In short, using a Mariner selected 'safe ZOC' value to influence the visualization and triggering of A&I in ECDIS.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 18/10/23**

New portrayal has been implemented in a branch of the PC. Contact NIWC on how to access and test it.

**Comment by TomRichardson6** [comment]
@alvarosanuy yes I recall drafting a proposal for the Singapore lab for this so I will revisit that and update it. Ideally noting the changes in the ECDIS performance standard it would be good to test both the symbology and the modifications to the alerts and indications catalogue. So maybe this has two parts as I guess the A&I element is not yet ready? 

To confirm the action here is on me to prepare a proposal to progress testing of this change.
