### ISSUE TITLE
Portrayal Impact Analysis - FC/DCEG 1.1.0 vs PC 1.0.2

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#114]
Below is a spreadsheet containing changes introduced by DCEG 1.1.0 _20221017 (**pre S101PT9 meeting**).

[20221202_S-101_PC Gap Analy1.0.2 vs 1.1.0_TR+AS.xls](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/10138283/20221202_S-101_PC.Gap.Analy1.0.2.vs.1.1.0_TR%2BAS.xls)

Note independent assessments done by TR and I in the last 2 columns of the document. The idea is, at the next PsWG meeting in January 2023, to confirm those entries that impact PC 1.0.2 and then create dedicated Github issues to resolve them by March 2023 (when we should have a PC 1.1.0 available in the GI Registry).

Please download the file and **come prepared to discuss you own assessment at the meeting**.

**PLEASE NOTE THAT:** Jeff is still working on the final version of the DCEG 1.1.0 and therefore new entries may need to be added to the list. I'll liaise with Jeff and upload any additional entries you may need to consider as well.

**Comment by alvarosanuy** [comment]
New version of the spreadsheet incorporating comments from Germany (Sylvia S.)
[20221202_S-101_PC.Gap.Analy1.0.2.vs.1.1.0_TR+AS+DE.xls](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/10204259/20221202_S-101_PC.Gap.Analy1.0.2.vs.1.1.0_TR%2BAS%2BDE.xls)

**Comment by alvarosanuy** [comment]
New version of the spreadsheet incorporating comments from Sweden (Klas)
[20221202_S-101_PC.Gap.Analy1.0.2.vs.1.1.0_TR+AS+DE+SE.xls](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/10212550/20221202_S-101_PC.Gap.Analy1.0.2.vs.1.1.0_TR%2BAS%2BDE%2BSE.xls)

**Comment by alvarosanuy** [comment]
New version of the spreadsheet incorporating comments from NIWC - **Please note that after comparing the 'changes log' spreadsheet originally provided by JW just previous to S101PT9 and the '_Summary of Substantive Changes in Edition 1.1.0_' table at the beginning of the DCEG 1.1.0 version submitted to the S100WG7 meeting (Dec 2022) , I noticed a number of new entries that will need your assessment (refer to rows 43 to 69).**

[20230106_S-101_PC.Gap.Analy1.0.2.vs.1.1.0_TR+AS+DE+SE+NIWC.xls](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/10357350/20230106_S-101_PC.Gap.Analy1.0.2.vs.1.1.0_TR%2BAS%2BDE%2BSE%2BNIWC.xls)

**Comment by DavidGrant-NIWC** [comment]
Updated with our assessment.

[20230106_S-101_PC.Gap.Analy1.0.2.vs.1.1.0_TR+AS+DE+SE+NIWC.xls](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/10362979/20230106_S-101_PC.Gap.Analy1.0.2.vs.1.1.0_TR%2BAS%2BDE%2BSE%2BNIWC.xls)

**Comment by alvarosanuy** [comment]
**Consolidated version to be discussed at the upcoming sWG meeting in January 2023:**

[Gap analysis_LAST version.xls](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/10370181/Gap.analysis_LAST.version.xls)

**Comment by MikusRL** [comment]
My only comment to the Gap analysis document is about the DCEG 14.6 update. As I understand waterLevelEffect attribute is added to the Offshore Production Area feature to be able to portray floating wind turbines vs the fixed ones. As I understand that the floating wind turbines are more dangerous for close navigation than the fixed ones because of the mooring chains stretches widely, and other moving underwater cables can be unseen and close to the surface. 

And then the sloping symbol versions created under the issue #68 should be used in portray, if the attribute waterLevelEffect is encoded as floating.

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 11th January 2023**

1. Discussed and agreed final list of changes that impact portrayal (see below)
[Gap analysis_1.0.2_1.1.0_Final Impact analysis.xls](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/10398574/Gap.analysis_1.0.2_1.1.0_Final.Impact.analysis.xls)

2. **Alvaro** to update existing Github issues with final portrayal instructions whenever different to the ones originally agreed/proposed by this subWG (e.g. due to the implementation of a different feature modelling, etc).
3. **NIWC** - Commence portrayal updates and seek clarifications when required.
4. A **PC 1.1.0 version** is to be f**inalised and uploaded to the IHO Registry by the end of March 2023** (the subWG noted dependencies with the publication of the FC 1.1.0, which is still in progress).

**Comment by DavidGrant-NIWC** [comment]
It's a little unclear whether the intent is:
1.  NIWC use the spreadsheet to create issues within the PC repo
2.  @alvarosanuy use the spreadsheet to create/update issues within this PSWG repo
    *  NIWC will link to these issues from the PC repo.

We recommend (2). If this has already been completed, then this issue can be closed.

**Comment by alvarosanuy** [comment]
@DavidGrant-NIWC  - Can you please have a look at the 24 entries in the 'IMPACT' tab of the spreadsheet attached to my last comment above (PsWG meeting decision) and create issues in your Github space (all linked to this PsWG space # 114) to track amendments to the PC if still required???
If you feel there's an entry in the spreadsheet that needs clarification or further discussions please create a new Github issue in this Github space.

**Comment by DavidGrant-NIWC** [comment]
Tracking for creation of the following issues:
* [x] BuoyNewDangerMarking: rename to BuoyEmergencyWreckMarking.
  * [PC issue #162](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/162)
* [x] Crane: throw error on curve geometry.
  * [PC issue #165](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/165)
* [x] FoulGround: throw error on curve geometry.
  * [PC issue #166](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/166)
* [x] InformationArea: throw error on curve geometry.
  * [PC issue #167](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/167)
* [x] DockArea: removed from skin of the earth.
  * #121
* [x] LockBasin: removed from skin of the earth.
  * #121
* [x] active submarine volcano (CATOBS = 21): must have point geometry.
  * [PC issue #168](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/168)
* [x] TwoWayRoute: added surface and scaleMinimum.
  *  #87 
  * [PC issue #145](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/145)
* [x] DeepWaterRoute: added surface and scaleMinimum.
  * #81
  * [PC issue #151](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/151)
* [x] TrafficSeparationScheme: added surface and scaleMinimum.
  * #86
  * [PC issue #146](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/146)
* [x] ArchipelagicSeaLane: added surface and scaleMinimum.
  * #80
  * [PC issue #152](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/152)
* [x] AnchorageArea.categoryOfAnchorage=15 must have point geometry. Throw error otherwise.
  * [PC issue #169](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/169)
* [x] DCEG 21.2 - row 16. Marked TBD?
  * [OBE](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/114#issuecomment-1432206252)
* [x] DCEG 27.166 - row 17. New boolean attribute synthetic AIS aid to navigation. Seems this is not in DCEG 1.1.0?
  * [OBE](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/114#issuecomment-1432206252)
* [x] LightFlareAndDescription: flareAngle rename to flareBearing.
  * [PC issue #170](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/170)
* [x] LightSectored: sector extension length should be 5mm.
  * https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/26#issuecomment-1182664153
  * [PC issue #10](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/10)
* [x] SeparationZoneOrLine/TrafficSeparationZone/TrafficSeparationLine:
  * [PC issue #172](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/172)
* [x] LocalMagneticAnomaly: update rule to reflect modeling changes.
  * #102
  * [PC issue #73](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/73)
* [x] IslandGroup: added surface and scaleMinimum.
  * #83 
  * [PC issue #149](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/149)
* [x] MooringTrot: added surface and scaleMinimum.
  * #84
  * [PC issue #148](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/148)
* [x] RangeSystem: added surface and scaleMinimum.
  * #85 
  * [PC issue #147]https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/147)
* [x] FairwaySystem: added surface and scaleMinimum.
  * #82
  * [PC issue #150](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/150)
* [x] LightSectored: UOM for sectorLineLength changed from metres to nautical miles.
  * attribute type changed from integer to real
  * resolution is 0.01 nautical miles.
  * [PC issue #171](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/171)

**Comment by alvarosanuy** [comment]
> * [ ]  DCEG 21.2 - row 16. Marked TBD?
> * [ ]  DCEG 27.166 - row 17. New boolean attribute synthetic AIS aid to navigation. Seems this is not in DCEG 1.1.0?

These 2 activities were not implemented. Original PsWG plans were reverted at S101PT9.
Therefore mark these 2 entries as completed (No action required really).

Refer to https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/70 on how to proceed with portrayal of 'Physical AIS'

**Comment by alvarosanuy** [comment]
> [ ] LocalMagneticAnomaly: update rule to reflect modeling changes.

It has been implemented via https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/102

**Comment by DavidGrant-NIWC** [comment]
Issues have been created for all entries - recommend close this issue.

**Comment by alvarosanuy** [comment]
Implemented in PC 1.1.0
