### ISSUE TITLE
categoryOfCargo = 7 (dangerous or hazardous cargo) for other features than Berth

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#116]
In regards to the S10PT decision on the need for a unique symbol related to categoryOfCargo = 7 (dangerous or hazardous cargo) for **Berth** - Refer to https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/112 

I would like to discuss the need to extend this intent to other features such as **AnchorBerth** and **Anchorage**. 

In S-4 there the magenta ‘flame’ symbol for ‘dangerous cargo’ (F19.3) is also linked to these two objects: 

**Anchorage areas: B-431.3 N12.7**

![image](https://user-images.githubusercontent.com/70189016/211671669-3dc2f6ad-d2fa-4084-b8be-cd0d055eec3d.png)
 

**Anchor Berth: B-431.2 N11.1**
 
![image](https://user-images.githubusercontent.com/70189016/211671752-16da6ba9-30ba-44eb-825e-b38dd5daca6e.png)
 

Note that S-52 does not link neither of these features to a distinct symbol. Only CATACH=8 is used to alter default portrayal for Anchorage Areas.

The other element to note is that CATACH includes value 4 (explosives anchorage) and, when you read its description, it sounds a lot like a ‘dangerous cargo’ anchorage. In fact, ‘explosives’ is one of the items classified in the IMO’s International Maritime Dangerous Goods (IMDG) code. 

What I’m trying to ask is: for consistency, wouldn’t the same driver that took us to include (and uniquely depict) dangerous cargo berths justify a similar approach for **AnchorBerth** and Anchorage features with **categoryOfAnchorage** = 4?? 

Wouldn’t make more sense to remodel CATACH by either adding a new value for Dangerous Cargo (and retire 4 from the list) or, if allowable, simply renaming value 4?

**Comment by MikusRL** [comment]
According to the S-52 PresLib symbol ACHBRT07 is covering the S-4 B-431.2, but I do not know how that practically works on ECDIS portray, as the symbol has a circle in the middle of the anchor, but does it expand somehow to accommodate the names and symbols? Who could elaborate on that? If that works already, perhaps we can take the same approach for the newly created dangerous cargo berth symbol, to accommodate the flexibility of various length names/numbers.

![image](https://user-images.githubusercontent.com/72803214/211769072-30992c75-4af6-492d-af07-c9e6a5471a30.png)


Second question. 
If we consider bringing ENC portray closed to S-4, for N12.7 Dangerous Cargo Anchorage, should we create a new symbol as per the N12.7, or could we reuse the one we created in the circle for berth symbol? Or, because this symbol is more simple than the berths symbol, should we go with this more simple flame for both - berths and anchorages. I think it would be beneficial to choose one flame symbol in stead of two different ones. Should we go to NCWG with this question as well? Perhaps they could have a valuable opinion in this case too and it could benefit the S-4 as well, like in the case of merging the PD and PA recently.

![image](https://user-images.githubusercontent.com/72803214/211769693-5c851b41-f07e-4a1e-8ac4-8e0d33177672.png)
 vs 
![image](https://user-images.githubusercontent.com/72803214/211770608-1966cd54-7367-4d11-822b-9a33f77e5e8f.png)

**Comment by alvarosanuy** [comment]
**Anchorage area CATACH=4 would look something like this:**

![image](https://user-images.githubusercontent.com/70189016/235838883-a06e9f8c-781e-4ad9-aba0-1c0e55587da6.png)

**Anchor Berth CATACH=4 would look something like this:**

![image](https://user-images.githubusercontent.com/70189016/235839044-a3d26d9f-5ce8-4235-9c5a-e7d0a16572dc.png)


In both cases symbol BRTHDNG1 will require and 'x offset' from ACHARE07 and ACHBRT07

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 10/5/23**

- [ ] @MikusRL or @HolgerBothien to develop new symbols for **Anchorage** and **AnchorBerth** as per pervious comment. The side to side symbols (flame+anchor) should be compiled as one symbol.
- [ ] **NIWC** proceed with implementation once new symbols are developed and made available. One will be depicted in the center of **Anchorage** Surface when **CATACH**=4 and the other one on **AnchorBerth** when **CATACH**=4.
- [x] **Alvaro** to open a new DCEGsWG GitHub issue to discus the merits of either, creating a new categoryOfAnchorage value 11 (dangerous or hazardous cargo) or renaming **categoryOfAnchorage** value 4 (explosives anchorage) to the more generic term 'dangerous or hazardous cargo'. Done - Refer to https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/66

**Comment by alvarosanuy** [comment]
> * @MikusRL or @HolgerBothien to develop new symbols for **Anchorage** and **AnchorBerth** as per pervious comment. The side to side symbols (flame+anchor) should be compiled as one symbol.

@MikusRL & @HolgerBothien  - Any of you have some time to spare to prototype this new symbol??

**Comment by MikusRL** [comment]
@alvarosanuy Sorry for the delay in answer. I will create one within one to three days.

**Comment by HolgerBothien** [comment]
Thank you Mikus. I don't have much time currently and will be off for the next three weeks.

**Comment by MikusRL** [comment]
While working on this it raised a couple of questions. 

- First, the anchor berth. The NOAA Chart 1 gives the appreciation and good overview of the ECDIS symbol portray vs. the paper chart symbol portray. For anchor berth the text of berth number is placed on the right top. I assume that if this is the expected placing of the text then the additional symbol of the dangerous cargo will work directly on the left of the berth symbol. 

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/61454db0-bc6b-4dc3-9897-dd493cfa2c92)

- Second, the anchorage area. We have to split this in two - one where the Anchorage area is captured as a point geometry with no defined border (most likely for generalization on smaller scales - ACHARE02), and the other where the Anchorage area is captured as an area geometry where the border and center symbol (ACHARE51) is shown. 
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/cc1cfed7-103e-4380-88c5-8fb6b285de96)

- So, the NOAA Chart 1 shows that when captured as a point symbol then ACHARE02 is used. Here we could attach the Dangerous cargo symbol also directly on the left of the anchor symbol. Then there can be a chance these could be miss red. I think there is a reason why all the functionalities of the anchoring points and areas and anchor berth points are made only to be distinguished with the pick report - as there are so many different categories. And with starting to create symbol for one, we might be questioned why there are no symbols then for each "paper equivalent category" also for ECDIS, but only for dangerous cargo. Also if only anchor symbol is portrayed then it is easy to distinguish where is the center point (the coordinate). With two equal size point symbols side by side that is more ambiguous. 
- But the area center symbol is ACHARE51 symbol - a hallow, lighter and enlarged symbol, which is correct for floating center symbol. But in this case not to mislead the user for the added dangerous cargo point symbol - should it be hallow too(?), definitely light magenta too, and should be bigger or stay as small as original symbol, but should be then at the direct left(?), as the exclamation and "i" marks for the center symbols usually are on the bottom right and left.

I will create the symbols, but I am questioning if we have the right decision for the anchorage area symbols by picking only one category to be different symbolized than all the rest, and of this would not actually contribute now to more cluttered and different to S-57 portray than by sticking with the pick report as per the S-52. 
Also should we then consider the line symbol ACHARE51 as well, like interchanging anchors with the dangerous cargo symbol, or use the new created combined achare with dangerous cargo point symbol on the border? I feel we have not yet considered this symbolization deep enough and might not be able to back this symbolization change well (justify), if questioned.

**Comment by alvarosanuy** [comment]
Taking in consideration the concerns raised by @MikusRL, I propose we implement the new symbol for **AnchorBerth** only and leave the conversation around **Anchorage** (Point & Surface) open until our next meeting.

Pending actions are now:

- [x] @MikusRL to develop new symbol for **AnchorBerth** as per @alvarosanuy comment on May 3. The side to side symbols (flame+anchor) should be compiled as one symbol.
- [ ] **NIWC** proceed with implementation once the new symbol is created (use symbol ANCBDNG2 below. Map **AnchorBerth** Lat/Long to the center of the combined symbol). The new symbol is to be mapped to **AnchorBerth** **CATACH**=4.

**Comment by MikusRL** [comment]
@alvarosanuy 
I have created the symbol for AnchorBerth as per above. 
[ANCBDNG.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/11664507/ANCBDNG.zip)

I created two versions - ANCBDNG1 one to one joining the symbols, and ANCBDNG2 sizing the BRTHDNG1 to match the Anchor height.
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/aa4a64b5-3f65-4cc7-88e5-5173075f770a)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/a42d966a-9991-4a75-a86a-7b110cc13b49)

**Comment by alvarosanuy** [comment]
**The new symbol ANCBDNG2 has been submitted to the GI Registry on 06/06/2023.**

**Comment by TomRichardson6** [comment]
All

In terms of Test Datasets TDS 8 has been expanded and now includes a feature with Category of Cargo - 7

https://github.com/iho-ohi/S-101-Test-Datasets/blob/main/dev/cells/101AA00DS0008/6/101AA00DS0008.000

**Comment by mikan66** [comment]
> Taking in consideration the concerns raised by @MikusRL, I propose we implement the new symbol for **AnchorBerth** only and leave the conversation around **Anchorage** (Point & Surface) open until our next meeting.
> 
> Pending actions are now:
> 
> * [x]  @MikusRL to develop new symbol for **AnchorBerth** as per @alvarosanuy comment on May 3. The side to side symbols (flame+anchor) should be compiled as one symbol.
> * [ ]  **NIWC** proceed with implementation once the new symbol is created (use symbol ANCBDNG2 below. Map **AnchorBerth** Lat/Long to the center of the combined symbol). The new symbol is to be mapped to **AnchorBerth** **CATACH**=4.

@alvarosanuy, confirming  you intended "Berth" instead of "AnchorBerth"?  AnchorBerth does not have attribute _categoryOfCargo_.

**Comment by alvarosanuy** [comment]
> @alvarosanuy, confirming you intended "Berth" instead of "AnchorBerth"? AnchorBerth does not have attribute _categoryOfCargo_

@mikan66 - The new symbol is to be linked to **AnchorBerth** features with **categoryOfAnchorage** = 4 (explosives anchorage).
Also note that I have opened a new DCEGsWG GitHub issue to discus the merits of renaming **categoryOfAnchorage** value 4 (explosives anchorage) to the more generic term 'dangerous or hazardous cargo'. Refer to https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/66

**Comment by alvarosanuy** [comment]
1. Based on modelling changes to **AnchorBerth** introduced in S-101 1.2.0, the mapping of the new symbol ANCBDNG2 has to be amended from **categoryofAnchorage**=4 to **categoryOfCargo** = 7.

2. Recommend closing this issue and, if supported by the PsWG, open a new issue to task the NCWG the review of the current **AnchorageArea** mappings in S-101. Mikus comment made on the 5th of June above shows that many more 'combined' symbols could be created to represent different types of Anchorages. Instead of making a decision on 'dangerous cargo' anchorages in isolation, it would be beneficial to look at the 'extension' of the portrayal of **AnchorgaeArea** more holistically instead.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 18/10/23**

- [x] **NIWC** - Update **AnchorBerth** Rule and amend the current mapping of symbol ANCBDNG2 from **categoryofAnchorage**=4 (discontinued in FC 1.2.0) to **categoryOfCargo** = 7.
- [x] **Alvaro** to provide S101 Test dataset when Production tools are updated to use FC 1.2.0.
- [x] **Alvaro** to refer the '_review **AnchorageArea** mappings in S-101_' to the NCWG. Mikus comment made on the 5th of June above shows that many more 'combined' symbols could be created to represent different types of Anchorages. Instead of making a decision on 'dangerous cargo' anchorages in isolation, it would be beneficial to look at potential **AnchorgaeArea** portrayal changes more holistically instead.

**Comment by DavidGrant-NIWC** [comment]
Will implement in PC 1.2.0 - [PC #236](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/236)

**Comment by mikan66** [comment]
Existing AnchorBerth rule did not check for categoryofAnchorage=4.  Adding default symbol = 'ACHBRT07' else if categoryOfCargo=7 then symbol ANCBDNG2.

I think we still need test data for this situation.  Here is faked data mapping Berth to AnchorBerth
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/4913543/b7e46320-212c-44dd-8d01-da31350ae736)

**Comment by TomRichardson6** [comment]
@mikan66 ?I understand that TDS 16 will need to be updated to reflect the edition 1.2.0 modelling but could you expand on whether there are any further changes to test data required here?

Spec for TDS 16 can be found here

https://github.com/iho-ohi/S-101-Test-Datasets/blob/main/S-101_Test_DataSets/docs/Test%20Dataset%20Section%2016%20Specification%2020230905%20FINAL.docx

**Comment by mikan66** [comment]
We still need data for AnchorBerth with categoryOfCargo=7, and also cases with categoryOfCargo="other value", or no categoryOfCargo attribute to test both portrayal symbols.

**Comment by MatthewCraggs** [comment]
[101AU00439144.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/14204052/101AU00439144.zip)

@mikan66. I have attached a S101 ENC with the requested AnchorBerth features included in the top left corner of the cell. The Cell is FC1.2.0 so could also be handy for other testing purposes.

**Comment by alvarosanuy** [comment]
Implemented in PC 1.2.0 - Input from NCWG8 to be added into a new dedicated GitHub issue if required.

**Comment by MatthewCraggs** [comment]
### Below are the comments from NCWG9.

CategoryOfCargo = 7 (dangerous or hazardous cargo) for other features than Berth
for consistency, wouldn’t the same driver that took us to include (and uniquely depict) dangerous cargo 
berths justify a similar approach for AnchorBerth and Anchorage features with categoryOfAnchorage = 4??
Wouldn’t make more sense to remodel CATACH by either adding a new value for Dangerous Cargo (and 
retire 4 from the list) or, if allowable, simply renaming value 4?
Note, S-101 researched the additional information which was stored in the INFORM attribute as part of 
considering and making a use case for new symbols, this gave rise to the new waiting anchorage. 
DK: should this portrayal extend to other areas like Caution Areas or restricted areas? 
Tom Richardson: the anchorage areas have restriction attributes, so that can be included as required.
Australia presented with an anchorberth – should there be visible indications of the anchoring area on an 
ECDIS display?

The Chair suggested that the different anchorage has been visualised and not just the dangerous cargo.
UK said they should follow S-4.

The Chair – asked the group if some should be visualised – if there is a symbol in ENC then it should be used 
in this (S-4?) – would need some symbol creation for S-4.

ESRI agreed it was more efficient to reduce text and is better for the mariner – in S-101 said you can several 
options.

The Chair – the response would be to say yes to having symbols for all anchorage being in S-101 – would 
need to investigate the compactness of the symbol – certain categories anchorages would need a new 
symbol which don’t exist.

USA said they should take time to look over the symbols to use instead of text.

**_Outcome:_** NCWG agree but this would require creating a new symbol(s), also need to check that there are 
any existing symbols which could be used to support this requirement. 

**_ACTION_** 9/13: US volunteered to review the S-4 content regarding anchorage symbols and consider the 
requirements for new symbols for the categories that would require a specific symbol.
