### ISSUE TITLE
NIWC Testbed Update - Slide # 28 - SY(CHDATD01) symbol has no portrayal parameters

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#13]
**S-101PT5 Action 24** - Discuss paper S-101PT5-21

[S-101PT5_21_EN_NIWC Test Bed Report_S101PT5_V1.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5290033/S-101PT5_21_EN_NIWC.Test.Bed.Report_S101PT5_V1.pdf)

![image](https://user-images.githubusercontent.com/70189016/94633718-955a9100-0311-11eb-8c2a-e85225e7d617.png)

**Comment by DavidGrant-NIWC** [comment]
Since "Highlight date dependent" is a required Independent Mariner Selection, SY(CHDATD01) should use a unique viewing group rather than sharing a viewing group with INFORM01.

It may be desirable to include a viewing group layer which includes the viewing groups for INFORM01 (31030 and 31031) and CHDATD01, allowing the mariner to easily toggle all symbol annotations.

**S-52 PresLib 4.0.2**:
![image](https://user-images.githubusercontent.com/62906211/95344803-06f18c80-0888-11eb-8557-09421624b295.png)
![image](https://user-images.githubusercontent.com/62906211/95344862-14a71200-0888-11eb-9c6b-61b84af6f7b4.png)

**Comment by alvarosanuy** [comment]
Support unique viewing group for CHDATD01 but I'd prefer not to join it with 31030 and 31031.

**Comment by JeffWootton** [comment]
Agree with Alvaro's comment.

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144342162-73c00716-f12c-4ecc-9a3c-12e8af1bd3b8.png)

**Comment by DavidGrant-NIWC** [comment]
Current portrayal implementation (to assist in viewing group registration):
```
      <viewingGroup id="31032">
         <description>
            <name>Date dependent</name>
            <description>The object is present only during the indicated period</description>
            <language>eng</language>
         </description>
      </viewingGroup>
```

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 26/7/22**

1. **Alvaro** to register the Viewing Group 31032 in the Registry (see details provided by NIWC above)
