### ISSUE TITLE
New symbol EMAREGR2.svg added to PC 1.1.1

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-101-Portrayal-subWG/Working-Documents#130]
New symbol added to PC 1.1.1 to satisfy intent of #28 - see [PC issue 186](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/186)

NAVARE52.xml line style was updated to reference the new symbol.

Issue created for awareness/tracking/registration purposes - can close if implementation is approved.

### NAVARE52.xml
```
<?xml version="1.0" encoding="ISO-8859-1"?>

<?S100lineage source="S52Preslib4.0" format="S100Ed2" version="0.1" creationDate="2022-09-16"?>
<?S100Meta name="NAVARE52" exposition="boundary of anchor area with small craft moorings"?>
<lineStyle>
   <intervalLength>8.6</intervalLength>
   <pen width="0.32">
      <color>CHGRF</color>
   </pen>
   <dash>
      <start>1</start>
      <length>6</length>
   </dash>
   <symbol reference="EMAREGR2">
      <position>4</position>
   </symbol>
</lineStyle>
```

### EMAREGR2.svg
```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="daySvgStyle.css" type="text/css"?><svg xmlns="http://www.w3.org/2000/svg" version="1.2" baseProfile="tiny" xml:space="preserve" style="shape-rendering:geometricPrecision; fill-rule:evenodd;" width="3.61mm" height="1.96mm" viewBox="-1.8 -0.16 3.61 1.96">
  <title>EMAREGR2</title>
  <desc>Embedded symbol</desc>
  <metadata>
    <iho:S100SVG xmlns:iho="http://www.iho.int/SVGMetadata/5.0">
      <iho:Description iho:publisher="IHO" iho:creationDate="2023-03-22" iho:source="https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/186" iho:format="S100SVG" iho:version="1.0"/>
    </iho:S100SVG>
  </metadata>
  <rect class="symbolBox layout" fill="none" x="-1.64" y="0" height="1.64" width="3.29"/>
  <rect class="svgBox layout" fill="none" x="-1.64" y="0" height="1.64" width="3.29"/>
  <path d=" M -1.64,0 L 0.01,1.64 L 1.65,0" class="sl f0 sCHGRF" style="stroke-width: 0.32;"/>
  <circle class="pivotPoint layout" fill="none" cx="0" cy="0" r="1"/>
</svg>
```

**Comment by alvarosanuy** [comment]
Can somebody provide engineering drawings and SVG files for the 2 above as required?

**Comment by MikusRL** [comment]
@alvarosanuy I can for point symbol, could do it tomorrow or today afternoon, but in S-100Toolkit there is no tool to measure or portray **line or area symbols**, not for me at least. 

I have installed NIWCs testbead tools, but I am not a confident user of it yet. Would be happy to catch up and learn from Holger, Hugh or others, who have done that before for lines and polygons, so could close this gap for my contribution delivery options to this WG. Would actually suggest if there would be possible to gather in one room (virtual or better real) experts and pcs in a "side-session", then we could make this a small workshop/capacity building, to expand the ones who could contribute to the portrayal, first perhaps during S-101PT in summer and possibly also across domains, if we could have this aside also the S-100WG.

**Comment by MikusRL** [comment]
@alvarosanuy I have created the point symbol ingineering drawing, as well as saved the above two texts as files (assuming those texts are the ones @DavidGrant-NIWC added to the PC 1.1.1) and added in the zip file. 
[EMAREGR2.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/11188933/EMAREGR2.zip)

Sorry, someone still to provide the line engineering drawing as I wrote above.

![image](https://user-images.githubusercontent.com/72803214/230861241-e3b64f97-6690-4783-8404-f26b6f304d82.png)

**Comment by DavidGrant-NIWC** [comment]
@MikusRL please update the zip to reflect the symbol included in PC 1.1.1 (I also edited my original comment to reflect the current symbol - there was a correction for namespace issues).

**Comment by alvarosanuy** [comment]
Hi @DavidGrant-NIWC  & @MikusRL  - I can get the latest versions of NAVARE52.xml and EMAREGR2.svg myself from NIWC's PC 1.1.1.

**I need help with the Engineering Drawings for both new versions.**

Thanks!

**Comment by MikusRL** [comment]
@alvarosanuy I looked at the drawing in GI registry for the NAVARE52.xml and it looks correct for the color part, and in the symbol preview part it is almost not distinguishable in the image added to the table that the lower part is darker a bit than the dash part, so from that perspective I think that the engineering drawing for the line is ok as it is registered and can be re-used for registering the new version of the .xml file.  And the above drawing is then to be used for registering the new EMAREGR2.svg point symbol. The word file with the table is included in the zip file above also. And please then use the .svg file itself as included in the PC v.1.1.1 as David mentioned. Change mentioned by David does not impact the engineering drawing.

@DavidGrant-NIWC , @mikan66 But because the EMAREGR2.svg itself is 1.64mm in height (it was like that in S-52 and I measured also in the IHO Symbol builder to verify the new one), but the registered engineering drawing of the line is showing 1.62mm in height, would you think that the drawing dimensions should be updated in the engineering drawing to 1.64 or even more because of the added dash line as well? Could some portray implementations be possibly impacted, like line symbol's either dash or the bottom of the EMAREGR2 could be cut if the dimensions are retained as defined? Where would you check the actual height of the symbol, as there is no Line symbol builder by IHO KHOA tool released to us yet?

**Comment by alvarosanuy** [comment]
**I have registered:**

- a new symbol EMAREGR2 (SVG file as per PC 1.1.1 release)
- a new version of the complex line NAVARE52 (XML file as per PC 1.1.1 release). Retained "Preview' and 'Engineering Drawing' files.
