### ISSUE TITLE
Review registration of all viewing groups

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-101-Portrayal-subWG/Working-Documents#131]
Definition appears to be missing for many viewing groups

![image](https://user-images.githubusercontent.com/62906211/227253609-af230acc-faf8-44ad-9c26-dd09b6853369.png)

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 11/5/23**

- It was noted that this situation is the result of an incomplete migration performed when the GI Registry was established and populated for the first time using S-52 as source. It was mentioned that his activity was originally coordinated by the S100WG and executed by KHOA.
Accordingly the PsWG recommends this shortfall is communicated to the S100WG Chair for follow up and remediation.

- [x] **Alvaro** to include this issue in the PsWG report to S101PT10 and request S101PT Chair liaison with S100WG Chair and IHO Sec. for follow up and remediation.

**Comment by alvarosanuy** [comment]
**Decision made at S101PT10:**

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/c55e850a-954d-4359-824a-6bb0de91047b)

**Need volunteer/s to conduct this task on behalf of the PsWG.**

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 19/10/23**

Nobody volunteer to lead this work.

- [x] **Alvaro** - Report lack of progress to S101PT12.

**Comment by TomRichardson6** [comment]
@alvarosanuy I have started to review these and note that currently there are duplicate viewing groups with a valid status in the GI Registry. My review will be of the 161 items in the Registry not of the groups in the S-101 PC that may need registering. I will aim to complete the review by the end of the year so that the way ahead can be reviewed at PT12. My review will extract the name from the S-101 PC which corresponds to the registered VG ID. I can then shared the resulting list prior to making submissions.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 09/04/24**

Activity is still under resourced. No progress made. May require IHO special funds to get it resolved in Q12025. Links to other necessary GI Registry 'house keeping' activities 
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/132

 - [ ] **Alvaro** to talk to S101PT Chair and recommend including this issue in his HSSC16 report.

**Comment by alvarosanuy** [comment]
Refer to https://github.com/iho-ohi/S100Infrastructure/issues/20

CLOSE this issue.
