### ISSUE TITLE
Register symbols SAFCON70.svg - SAFCON99.svg

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-101-Portrayal-subWG/Working-Documents#145]
New symbols (to the S-101 portrayal - they are present in S-52) were added to label contours deeper than 99m; see [PC issue 233](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/233)

These symbols will need to be registered, but we may wish to hold off since they follow the current S-100 SVG schema. The S-100 SVG schema will likely be updated after the next S-100 WG meeting which will necessitate updating all of the symbols.

**Comment by alvarosanuy** [comment]
I will register them now because, at S101PT10 meeting, it was decided to explore the possibility for KHOA et al. to do a back end bulk SVG update to all the symbols registered in the GI Registry.
- [x] @DavidGrant-NIWC  - Can you please upload SAFCON70 to SAFCON99 SVG symbols as per the current schema?
- [x] @DavidGrant-NIWC or @MikusRL  - Can you produce and upload Engineering Drawings for SAFCON70 to SAFCON 99?

**Comment by DavidGrant-NIWC** [comment]
[SAFCON70-99.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/11770907/SAFCON70-99.zip)

**Comment by alvarosanuy** [comment]
> * [ ]  @DavidGrant-NIWC or @MikusRL  - Can you produce and upload Engineering Drawings for SAFCON70 to SAFCON 99?

 @DavidGrant-NIWC  @MikusRL  - Can you assist with this?

**Comment by DavidGrant-NIWC** [comment]
We haven't generated these drawings before so it would take us a while. We'd appreciate if @MikusRL could generate them...

**Comment by MikusRL** [comment]
@alvarosanuy I did not realized that there are 30 symbols. I made the first today. Pasting its image here. 

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/59a154e6-41c5-4a44-9ac4-f6e24b690896)

Please comment. 
@DavidGrant-NIWC Have I understood and drawn it correctly? I got confused a bit now about the pivot point... is it correct that it is still 0,0?, and then the symbol is shifted from it, as in the drawing shown? Because that is stated in the .svg, that pivot point is 0,0. And the measurements I take after loading this image in the S-100 Toolkit's Symbol builder tool:

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/fd47363d-ff57-479c-9f95-5f4b4f70be44)

The original S-57 drawing mentions pivot point as Pivot point column: 0.65 and Pivot point row: 1.25, but I understand that with the S-100 svgs the pivot point noting is different, or is it the coordinate reference which is different for the S-100 svgs, and the pivot point should be indicated from the S-100 svgs agreed reference point. Please clarify someone to make these rdawings correct. Thanks.

**Comment by DavidGrant-NIWC** [comment]
### S-100 SVG Pivot Point
There really is no "pivot point" concept in SVG. In S-52 the DAI could specify a pivot point, but in S-100 the symbols should always be designed so that the pivot point is at (0, 0). See S-100 9-B-2-1:<br/>
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/78e34ef2-16b2-45f8-bc11-3a8d9aa97393)

### Engineering Drawing Accuracy
It looks like the drawing may not be 100% accurate, but I suspect this is also the case for existing drawings. For instance, the distance from the pivot point to the center of the black line on the left of the symbol should be 3.52mm - the drawing shows 3.5mm. The width of the black line is 0.32mm, and the width of the blue line is 0.96mm. I can't tell what the 0.25mm labels in the drawing are supposed to represent.

### SAFCON symbol placement
The SAFCON symbols are designed so that the pivot point is in the (approximate) center of the label. The label is composed of one or more of the `SAFCONXX` symbols. Which symbols are used is determined by the number of digits in the label.

I didn't include the fractional symbols in the following table (`SAFCON5X` and `SAFCON6X`):

|# of digits in label|Symbols used to create label|Pivot point|Depth Range|
|:---:|:---:|:---|:---|
|1|`SAFCON0X`|Center of `SAFCON0X`|[0 to 10)|
|2|`SAFCON2X`,`SAFCON1X`|between 2X and 1X|[10 to 100)|
|3|`SAFCON8X`,`SAFCON0X`,`SAFCON9X`|center of 0X|[100 to 1,000)|
|4|`SAFCON3X`,`SAFCON2X`,`SAFCON1X`,`SAFCON7X`|between 2X and 1X|[1,000 to 10,000)|
|5|`SAFCON4X`,`SAFCON3X`,`SAFCON2X`,`SAFCON1X`,`SAFCON7X`|between 2X and 1X|[10,000 to 100,000)|

So, if you were to lay the following SVG symbols on top of one another: `SAFCON33`,`SAFCON22`,`SAFCON11`,`SAFCON70`, it should result in the label "3210" drawn to the screen, with the geographic position of the label (pivot point) between the digits "2" and "1".

**Comment by MikusRL** [comment]
@DavidGrant-NIWC Thank you for your excellent feedback! Looking at the rest of the SAFCON symbols I managed to figured that out. That is why I did set the question if the pivot point should be other this time than just 0,0. Based on the fact that the pivot point is defined in the S-100 itself and is constant I suggest we remove that line from the drawing to remove the possible mis-definition of it. It does not give any additional information, as you commented above. 

I will make sure I read the values precisely when adding them to the drawings, thanks. 

One suggestion though for the future - perhaps to ease a little bit the registration and focus on the svg itself more - we could state that the engineering drawings are not the official "truth" but gives only appreciation of the symbol - its general extents, supposed look in exaggerated scale (500% at the moment used throughout) and the supposed position in regards to the point where it is or will be defined, be it a part of the labels center point or the defined point geometry, or the areas center of gravity, etc. And the normative or the "to be used" always would be the .svg itself. The .svgs with the S-100 are free accessible vs the S-52 library, so should be no objections from that perspective, and it would drive the machine readability focus too. Once someone spots the mistake and gives feedback, it is fixed in the svg and everyone benefits, and in most cases I would hope that the drawing then would not need to be updated, as the general look and feel of the symbol could be not changed in the process - more efficient upgrading and maintenance of the symbols then possible. Your thoughts and can we go ahead with such a concept already now, or would there be needed some change of the texts in S-100. We could easily add the note in the GI registry that the drawing is only informative or indicative and the svg is normative and to be used in implementation.

**Comment by DavidGrant-NIWC** [comment]
In general I agree with your suggestions, but any changes to the symbol registration process would have to be discussed with @JeffWootton and @alvarosanuy, and should be handled outside of this issue. I'm not sure what the appropriate repo would be, so I guess it would have to be via email.

**Comment by MikusRL** [comment]
>It looks like the drawing may not be 100% accurate, but I suspect this is also the case for existing drawings. For instance, the distance from the pivot point to the center of the black line on the left of the symbol should be 3.52mm - the drawing shows 3.5mm. The width of the black line is 0.32mm, and the width of the blue line is 0.96mm. I can't tell what the 0.25mm labels in the drawing are supposed to represent.

I looked through all the svgs, and it looks like they are supposed to be in series, but they are not very "clean" in the way to be also drawn up to the 1/100 of a mm. It would not make a good sense to show all the precise precise mm as they are encoded right now. They either need to be cleaned and harmonized within their series (there are three series as I understand) or we can assume that they are good as they are encoded as no one would be able to make a distinction on screen of a 1/100 of a mm, and I would then create drawings which shows that harmony within the series - rounded up to 1/10 of a mm for the distance from the coordinate starting point (or called as a pivot point in other sense...). Otherwise the drawings would look like requiring fixing. And I will exclude the very small dimensions from the drawings, as I can not portray these dimensions so they are understandable and readable, again for the same reason - the svg is available and machine readable. No one will try to recreate the symbols manually from the drawings if they can just download and use the svgs.

The SAFCON90 misses one edge for the black line of the "0". 

All three "4" symbols are larger than the rest of the numbers. the SAFCON04 in the S-52 Annex A drawing shows that it should be the same external size as the rest of the symbols. Is that intentional for these new symbols that they are bigger, and that is expected to be shown in the drawings too?

**Comment by MikusRL** [comment]
The SAFCON90 "0" is also thinner - only 1.2mm. Please when you review the lines for it make sure it is also 1.25mm, and its side edges are straight. Thanks.

**Comment by MikusRL** [comment]
@alvarosanuy I have created the drawings. Please do the spot check to confirm all is ok. I have made the drawings as per above considerations and comments. I have not updated the svg files. Four svg files need to be updated to match the drawings - SAFCON90, SAFCON74, SAFCON84, SAFCON94.
[SAFCON70-99 drawings.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/11911579/SAFCON70-99.drawings.zip)

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/257d9fe2-a210-4cae-9076-c744f2b92a73)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/53bc0c24-10c2-4416-bc8b-1332f962826e)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/cab6a831-8c33-4503-8e58-a4aa1d481f81)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/9e222f88-8d8d-4ea3-9c69-4fc8f340f70a)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/b3e658d7-bfa9-43f9-ae06-ee9b1bb51e7f)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/59955063-01a9-467f-89f0-b0918a4afaf4)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/dcbf3f87-4e1a-4bbd-87c9-a289761c711c)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/c06d27a8-1ce3-4a8e-8671-7451066d58c5)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/20791d33-3e97-4bf3-85a2-6ffd06680407)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/7ac98eb3-d829-4557-80da-92b3995e02f8)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/1eaeac6b-887e-475a-8192-1f9139340869)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/e809d3c3-b356-4058-8e18-8ac0d5e6db27)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/9decb330-7c19-4337-ad07-6f09cef9706d)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/b2981472-9553-42c9-9ec5-09e75bacdce7)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/aa76d18c-8df9-42f6-a2fc-5de67d6ac4a7)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/0e458b86-4a0d-4169-a797-31baa6edad62)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/3d8b550d-1cba-4f77-a38b-8a96fcb049b3)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/b6c00f30-53c5-4221-87b7-227eefc82e98)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/e32a3761-a4dd-44c6-b0ed-54e4b15d31ad)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/a7180af6-4a51-43af-bf2b-d8623cdda966)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/f27b824d-7218-4528-a054-00b81ff0708c)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/9ecc7957-24af-4ecb-87a1-0aa7cad69c94)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/2abddfd3-42ff-418b-8698-025bea5ac248)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/2e449828-2f5c-4e92-842a-1d6be3881880)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/93813679-5646-43d8-92a4-3e25f534193a)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/171233f7-f0bd-489c-903e-36c03c68aa72)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/513c50e1-c94f-41e9-8630-67a58755ecf9)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/588148cd-5b49-49a7-8452-1acdcf3b9489)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/51e0858a-94d1-4999-9bf6-bf120ee50e42)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/34a068dd-40cd-4e77-8b35-d4adc0dee176)

**Comment by DavidGrant-NIWC** [comment]
> Four svg files need to be updated to match the drawings - SAFCON90, SAFCON74, SAFCON84, SAFCON94.

### Issues
|Symbol(s)|Issue|SVG needs update|Drawing needs update|
|:---|:---|:---:|:---:|
|`SAFCON71`,`SAFCON91`|Right edge of symbol is clipped|Y|Y|
|`SAFCON74`,`SAFCON84`,`SAFCON94`|DAI file doesn't match S-52 appendix<sup>1</sup>|N|Y|
|`SAFCON76`|Top edge of symbol is clipped in the drawing|N|Y|
|`SAFCON90`|Currently matches the S-52 DAI file, but should be updated to match the drawing<sup>2</sup>|Y|Y|

1. All of the "fours" have this issue, not just the new ones. The S-52 DAI file matches the S-101 SVGs. The S-52 engineering drawings don't match the DAI file. I believe since ECDIS systems have been using these symbols for many years that we should retain the current symbol size and update the engineering drawings to match. The ENCWG should be notified of the discrepancy.
2. The S-101 SVG matches the S-52 DAI file. The S-52 DAI file appears to be in error since `SAFCON90` is the only "zero" that doesn't match the others. The ENCWG should be notified of the discrepancy, and we should update our `SAFCON90` to match the other "zeros".

### Recommended Actions
If @alvarosanuy agrees, I recommend that:
- [x] @DavidGrant-NIWC to notify ENCWG of issues noted above.
- [x] @DavidGrant-NIWC to update the following symbols: `SAFCON71`, `SAFCON90`, and `SAFCON91`.
- [x] @MikusRL to update the drawings of `SAFCON71`, `SAFCON90`, and `SAFCON91` once the symbols are updated.
- [x] @MikusRL to update the drawings of `SAFCON74`, `SAFCON84`, and `SAFCON94` to match the symbols (1.55mm wide, 2.98mm tall).

**Comment by MikusRL** [comment]
@alvarosanuy Sorry for the long delay in finishing this task. I trust I can find the time to do this during this week.

@DavidGrant-NIWC where can I find your updated SAFCON71, SAFCON90 and SAFCON91 svgs please? Or could you upload them here in a new .zip please? Thanks.

**Comment by DavidGrant-NIWC** [comment]
@MikusRL you can grab the updated symbols from the S-101 PC: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/tree/main/PortrayalCatalog/Symbols

**Comment by MikusRL** [comment]
@alvarosanuy 
I have updated the drawings as per the David's two last points. My apologies for late execution.
[SAFCON71 74 84 90 91 94.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/12477348/SAFCON71.74.84.90.91.94.zip)

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/061a5aa5-d5fa-40f7-9727-5dc5b6e3d797)

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/f60933d8-1f38-4ea1-ad3a-b041cc128598)

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/fb24f9a0-4817-4b59-8666-350dd15fdcaf)

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/cc0202c8-78d1-4dfe-9faa-c9615a0a907c)

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/017d3256-82af-4e37-8078-cfe1dfcbd1bf)

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/72803214/68ab341e-5f5b-49f2-87c2-9e2789fa3264)

**Comment by alvarosanuy** [comment]
> [ ] @DavidGrant-NIWC to notify ENCWG of issues noted above.

Has this been done?

Apart from that it seems the PC should be complete by now (?)

I'm still in the process of registering the new symbols in the GI Registry.

**Comment by DavidGrant-NIWC** [comment]
> [ ] @DavidGrant-NIWC to notify ENCWG of issues noted above.

> Has this been done?

It has now 😃 

> Apart from that it seems the PC should be complete by now (?)

Yes and no. The symbol review is identifying clipping issues with the symbol boxes in some cases (mostly when line styles wider than 0.32mm are used). This only affects the symbols, not the drawings. I assume these issues can be corrected as part of an overall symbol review.
|Left edge|Bottom edge|Right edge|
|:---:|:---:|:---:|
|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/06502b26-1dc7-4a06-aea9-047bee86c612)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/169c996f-a7f8-4bcc-b1f9-1ac5dde9c2cb)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/bfbcbbff-0e3f-4a76-b452-819c72116c4b)

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 18/10/23**

The PsWG recognized that are clipping issues with some (a minority) of the symbol boxes, but these are probably not noticeable in ECDIS.

A decision was made to proceed with registration of the symbols and close this issue when done.

- [x] **Alvaro** to Register symbols SAFCON70 to SAFCON99 in the GI Regitry and close this issue when done.
