### ISSUE TITLE
Local Magnetic Anomaly - Portrayal of Curves & Surfaces

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#148]
S-52 LUT use Grey and not magenta colour to depict **LOCMAG** linework Area features.

<img width="542" alt="image" src="https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/7fe8c6f8-ba20-4d38-9258-325045947395">

I propose the following changes for the portrayal of **LocalMagneticAnomaly** features in S-101 :

- [ ] **Curve** - Do we really need Curves for this type of feature?? 

- [ ] **Areas Plain Boundaries** - Propose replacing SY(LOCMAG51);LS(DASH,1,CHGRD) with SY(LOCMAG51);LS(DASH,1,CHMGD). LOCMAG51 will sit in the middle of the area.

- [ ] **Areas Symbolized Boundaries** - Propose replacing SY(LOCMAG51);LC(NAVARE51) with SY(LOCMAG51);LC(CTYARE51). LOCMAG51 will sit in the middle of the area.

- [ ] Also, I propose we incorporate the magnetic anomaly value label to all 3 geometry types (Point, Curve & Surface). Refer to https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/102

- [ ] Propose magnetic label colour is amended to CHMGD. Testing has demonstrated they are hard to read when CHMGF
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/d0ae8f23-076b-479f-ae0b-b8a1c1618382)

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 18/10/23**

- [x] **NIWC** - Amend colour of Curve and Surface linework to CHMGD
- [x] **NIWC** - Update colour of magnetic legend (all geometries) to CHMGD
- [x] **NIWC** - Produce screenshots with deep and shallow background in Day, Dusk and Night modes.
- [x] **NIWC** - Repeat the action above but using Black colour for legends.
- [ ] **PsWG** - confirm magnetic legend colour preference for PC 1.2.0 once screenshots are uploaded to this issue.

**Comment by DavidGrant-NIWC** [comment]
The centered area symbol looks a little odd now since it's a different color (CHMGF) then everything else (CHMGD).

Also, the appearance is no longer consistent with `MagneticVariation` features, which use black labels and a mix of CHMGF and CHMGD (and no area outline):
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/620fc704-da32-4a06-be69-9cee13549069)


|Plain Boundaries|Underlying Depth|Labels|Day|Dusk|Night|
|:---:|:---:|:---:|:----:|:---:|:---:|
|Off|Shallow|Black|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/a884b4a9-e737-488f-80dd-42d05788207c)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/ddcc4ce4-b8bb-43c4-86ad-b93c6710b650)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/e20d9fb0-304d-4a1f-9623-df500060122b)|
|On|Shallow|Black|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/bedf98fe-c189-4b5c-9c2f-73487369a417)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/5f5bb993-0a70-48d4-9836-b784a040016c)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/442b29ad-12ab-4323-879c-d9c77a8bc0af)|
|Off|Deep|Black|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/20aabc01-6b67-46ac-8d32-1e715212579e)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/598cddab-3cf9-4529-9718-263003584f90)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/bd29ab46-4453-4da8-be65-39523049423f)
|On|Deep|Black|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/f8b345a3-6285-49a7-9872-4a1bca60333a)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/4a85ae8d-6c98-48cf-a704-8c5acc30877d)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/62946356-374d-4590-b4ea-3acb29201357)|
|Off|Shallow|CHMGD|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/eb20b96e-8a19-43e5-acb9-fec17a9d737e)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/35002077-155c-469f-806e-7b118561f13c)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/a19fdb53-277b-4cf5-9b0e-ecc50613d86a)
|On|Shallow|CHMGD|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/d441c5b8-de85-45c1-8e88-4a8a80ccfb9d)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/433ae41c-1063-4093-ae23-ef0ebb8272f9)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/96bc7a11-3a35-4a54-926e-ad0079f4d1aa)
|Off|Deep|CHMGD|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/99bd6b1b-71ae-4a8b-94c7-40e4ef51c99e)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/d3dca6c0-aea9-43fe-8c8a-5253c21426d9)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/ec4254b9-a4f3-417d-9c94-a9d908a67193)
|On|Deep|CHMGD|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/b2131c2b-1953-4671-84e5-952f2a0a6241)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/60e6031b-ee6a-4874-a587-43e4c76cf51b)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/34210990-bede-4e5c-8323-34c171f6a3b3)

**Comment by alvarosanuy** [comment]
> Also, the appearance is no longer consistent with `MagneticVariation` features, which use black labels and a mix of CHMGF and CHMGD (and no area outline):

I believe the best way forward is to keep it simple. Therefore I propse:

Retain **LocalMagneticAnomaly** portrayal as per S-52 wit the following 3 exceptions only:

- [ ] Add magnetic legend (text) to all geometries using Black colour (as per **MagneticVariation** features).
- [ ] **Areas Plain Boundaries** - Replace SY(LOCMAG51);LS(DASH,1,CHGRD) with SY(LOCMAG51);LS(DASH,1,CHMGD). LOCMAG51 will sit in the middle of the area.
- [ ] **Areas Symbolized Boundaries** - Replace SY(LOCMAG51);LC(NAVARE51) with SY(LOCMAG51);LC(CTYARE51). LOCMAG51 will sit in the middle of the area.

Point Geometry - Simplified and Paper Chart Point options stay as per S-52.
Curve Geometry - As per S-52

**Comment by DavidGrant-NIWC** [comment]
| [...] LOCMAG51 will sit in the middle of the area.

`LOCMAG51` has a large offset. Do you mean that the _pivot point_ will sit in the middle of the area?

- [x] Add magnetic legend (text) to all geometries using Black colour (as per MagneticVariation features).
- [x] Areas Plain Boundaries - Replace SY(LOCMAG51);LS(DASH,1,CHGRD) with SY(LOCMAG51);LS(DASH,1,CHMGD).
- [x] Areas Symbolized Boundaries - Replace SY(LOCMAG51);LC(NAVARE51) with SY(LOCMAG51);LC(CTYARE51).

|Plain Boundaries|Underlying Depth|Day|Dusk|Night|
|:---:|:---:|:---:|:---:|:---:|
|Off|Shallow|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/a9dd6012-7aec-4f54-a717-dd14e392b9b3)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/52df6f00-3f21-4a3d-9850-32a81fb02d88)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/87155afa-6de7-48fa-88fc-09e0cb989e37)
|On|Shallow|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/6c73bc57-d8b3-46f8-9a76-3da4661721dc)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/2d1bc83b-a70b-4866-9d38-838b41b7ad1c)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/0a16e192-9b4c-4149-a85e-c2f1beddcf2e)
|Off|Deep|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/5b6038b7-6392-4c06-9954-447c9fe39615)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/3300166d-4541-4a8d-a65a-abd2055b2d33)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/c26b14cb-c940-47a1-9b34-e168750049a4)
|On|Deep|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/6f15ae6f-48e2-4f11-b2a6-469a35c1045b)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/dda5f3f3-dc29-4e3f-95da-22ed54b399c6)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/b4b03f31-b23a-455e-95c1-6a1e181d8798)

**Comment by alvarosanuy** [comment]
> `LOCMAG51` has a large offset. Do you mean that the _pivot point_ will sit in the middle of the area?

Leave as is for now.

Unless I hear something different I would proceed and CLOSE this issue on Monday 27/11/23.

**Comment by DavidGrant-NIWC** [comment]
[PC issue 283](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/283) has been closed based on @alvarosanuy comment of 20NOV23. Recommend this issue is closed as well.
