### ISSUE TITLE
NIWC Testbed Update - Slide # 33 - IEC 61174 (4.18) Default selector requirement

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#15]
**S-101PT5 Action 24** - Discuss paper S-101PT5-21

[S-101PT5_21_EN_NIWC Test Bed Report_S101PT5_V1.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5290033/S-101PT5_21_EN_NIWC.Test.Bed.Report_S101PT5_V1.pdf)

![image](https://user-images.githubusercontent.com/70189016/94640398-ee322580-0321-11eb-8325-6c629b2ac2ed.png)

**Comment by DavidGrant-NIWC** [comment]
- S-100 Part 9 does not support text groups or text group layers
    - NIWC S-101 PC implements S-52 text groups as S-101 viewing groups
    - NIWC S-101 PC implements S-52 text group layers as S-101 viewing group layers
- S-52 text groups / text group layers are not affected by, and do not affect, Display Mode selection
    - e.g. Changing a text group layer such as "Important Text" does not change the display mode from "Standard"
- 61174 requirement cannot be met by S-101:
    - Changing "Important Text" in S-101 changes a viewing group layer, which changes the display mode

This issue poses challenges for synchronization of display mode / text groups in dual-fuel operation.

**Comment by alvarosanuy** [comment]
Agree that:
 - Selecting 'Standard'display mode shouldn't activate 'Important text'. 
- Activating 'Important text' when DM is 'Standard' should not change it to 'Other'.

Also:
- S-52 (and S-98 Annex C) indicates that "All text is in the IMO Category “Other Information” but IEC 61174 requires "Important Text' to be included in the Default ECDIS settings alongside the 'Standard' display content.
- OEMs must develop their system in a way it guarantees that, when ECDIS is turned ON (or is requested to revert to Default settings), IEC 61174 Table 3 options come up 'as listed'.

**Possible options to overcome this issue?**

**Comment by DavidGrant-NIWC** [comment]
> Possible options to overcome this issue?

A) Add support for text groups / text group layers to S-100 Part 9

B) Modify S-100 Part 9 so that independent groups of display modes could be specified, e.g.
  - Group 1: Base, Standard, Other
  - Group 2: Mariners Base, Mariners Standard, Mariners Other
  - Group 3: Text Base, Text Standard, Text Other

Either of these changes would also require updates to S-100 Part 2b (portrayal register).

**Comment by alvarosanuy** [comment]
We recommend:

- the S101PT to support NIWC's view that the S-100 standard requires amendments and
- NIWC to prepare and submit a paper to the upcoming S100WG meeting outlining options A and B for their decision.

**Comment by DavidGrant-NIWC** [comment]
A fundamental issue that we cannot resolve is whether text is part of IMO display category / display mode "Other Information".
* If yes, 61174 has a conflicting requirement.
* If no, S-52 / S-98 contains incorrect information.

We cannot propose a way forward without an agreement on the requirements.

**Comment by DavidGrant-NIWC** [comment]
Based on feedback from Furuno and SevenCs, S-52 text groups are independent of the display mode.

We have a third implementation option for support of text groups:

C) Update the S-101 Portrayal Catalogue so that viewing group layers associated with text are not included in any of the catalogued display modes. This implements the viewing group layers independently of the display mode, and requires no document or schema changes to either S-100 Part 9 or S-100 Part 2b.

The drawback to this option is that it may be confusing to the mariner unless the user interface in the OEM system clearly distinguishes these independent viewing group layers from the viewing group layers which are associated with a display mode. It is also less flexible than option B (independent groups of display modes) for products which might be better served by multiple display modes, however this is not an S-101 issue.

From an S-101 perspective, we recommend resolving this issue via option C.

**Comment by DavidGrant-NIWC** [comment]
Option C implemented in the test bed. Viewing group layers implementing text are independent of the display mode:

https://user-images.githubusercontent.com/62906211/105915930-417d6180-5ffe-11eb-8c75-9b4e03ce63ae.mp4

**Comment by DavidGrant-NIWC** [comment]
Recommend close - implemented using option C as demonstrated above.

**Comment by alvarosanuy** [comment]
Decision made and changes applied to PC.
Broader communication to ENCWG and S100WG still open as S101PT actions PortSG-23 and PortSG-24.
