### ISSUE TITLE
Portrayal of Distance Mark

### ISSUE THREAD

**Issue by HermanSchouten** [S-101-Portrayal-subWG/Working-Documents#162]
The Boolean attribute Distance mark visible should also control the presentation of the feature in S-101.  
To resemble presentation in S-4
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/90600414/42443e9b-3055-4b99-831a-e5990c3a38eb)
So if the distance mark is visible, use the portrayal in black.
If the distance mark is not visible keep current portrayal in magenta.

In many (our) cases Distance marks are just minor posts which do not have a Parent feature. Or could even be a Distance mark painted on the Quay (SLCONS), it is visible but without Parent feature. In such cases you still would want black instead of magenta display.

Dave has pointed out all the good work already done to improve the portrayal of distance mark. https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/39
Making this adjustment would definitely be appreciated by data producers.

**Comment by alvarosanuy** [comment]
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/5e002f38-0bd5-4bf5-ae04-9c59b2770a4f)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/20ebec77-0924-49c0-b358-993c86b852d1)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/4371b258-15e0-4111-b35a-10809004d3d6)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/14b84e46-8b16-4f44-9009-360fbd05c395)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/da186f83-37f3-4452-a933-824b62b15444)

**An option** could be depicting the mark using a small black circle (similar to DISMAR05 - InlandENC) and the corresponding **measuredDistanceValue** when **Distancemark** is associated to Curve or Surface features (i.e. ShorelineConstruction).

**Comment by HermanSchouten** [comment]
I would rather have the boolean attribute manage the presentation. This will ease conversion from S-57 to S-101.
The definition of a distance mark already has the structure feature in it. 
Adding a parent feature only makes sense if the parent is a significant feature. Like you would do on paper charts.

**Comment by alvarosanuy** [comment]
**Updated version of DCEG regarding non-compulsory requirement for Structure/Equipment relationship**

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/43bd123b-ab8a-4ab3-a191-ae81a7260d27)

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 10/04/24**

- Approve development of new black version of symbol DISMAR06 to be used when **distanceMarkVisible**=True and the feature does not share spatial with other Point feature. When it does, only the text label is to be displayed using the current offset mapped in PC 1.2.3.
- When the **DsitanceMark** does not share spatial with another Point feature, the text label is to be displayed to the right of the 'circle' as per current encoding for when **distanceMarkVisible**<>1.

@JeffWootton - Have we decided to make **distanceMarkVisible** mandatory?

@RichardCoyles - Can you create SVG+ED of the new black symbol using DISMAR06 as the starting point? I noted DISMAR05 (InlandENC) is an existing symbol in the GI Registry but it seems to be missing the center point and its line thickness looks thinner than DISMAR06..

**Comment by JeffWootton** [comment]
@alvarosanuy: `Have we decided to make distanceMarkVisible mandatory?` Yes, based on the decision made at the meeting that portrayal (black or magenta) will be based on the population of this attribute.

**Comment by alvarosanuy** [comment]
**Can the UKHO (or others) assist with the task outlined below?**

> @RichardCoyles - Can you create SVG+ED of the new black symbol using DISMAR06 as the starting point? I noted DISMAR05 (InlandENC) is an existing symbol in the GI Registry but it seems to be missing the center point and its line thickness looks thinner than DISMAR06..

**Comment by alvarosanuy** [comment]
New **DistanceMark** portrayal files (Black):

[DISMAR07.zip](https://github.com/user-attachments/files/15998660/DISMAR07.zip)

- [x] **Alvaro** to process registration in the GI Registry
- [x] **NIWC** to update corresponding Rule to use DISMAR07 when **distanceMarkVisible**=True

**Comment by MikusRL** [comment]
Thank you for creating the symbol. Sorry for being late. 

My considerations when I volunteered for the symbol. Perhaps still need to be quickly discussed through before final registration and application in the PC.  
1) There are similar symbols in registry already - POSGEN 03 and 04. Not exactly alike but to consider. I guess that because the new DISMAR07 would always(?) be with the distance value label, it won't be able to mix the new symbol for these.
2) There is a NOTBRD11 which could potentially be considered to use in the portray if the distance mark is visually conspicuous. Is the number usually on the board or alike? Of course there could be an issue to portray it on top of building or alike. But so would it be for the new symbol. Should it have some offset from the building or other structure symbol?
3) Although the DISMAR07 symbol is black, I assume that the distance value still would be encoded beside them as magenta?
4) There is DISMAR03 registered. Does it need to be considered to be created as well as new symbol with the circle in black or is this particular symbol applicable only in the center line of the river, therefore always non existent and therefore magenta only?

@alvarosanuy @DavidGrant-NIWC But if this is already discussed, and is actually strait forward to implement in the PC, then please ignore the above considerations.

**Comment by DavidGrant-NIWC** [comment]
> Although the DISMAR07 symbol is black, I assume that the distance value still would be encoded beside them as magenta?

I assume from the original request the text should be black in this case (as shown below).

Note: The portrayal checks for a StructureEquipment relationship rather than comparing the spatial.

I don't have real test data, but this should be representative:
|`distanceMarkVisible`|Result|
|:---:|:---:|
|`true`|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/2b2f180d-86e1-450a-8b06-0b55755e109b)|
|`false`<br/>(except leftmost)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/0e65acf3-78ed-47a5-a3dd-87e146712766)|

**Comment by alvarosanuy** [comment]
Implemented in PC 1.4.0
