### ISSUE TITLE
Light Sector portrayal - Sector arc extension

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#26]
This issue is the result of the discussions maintained at Issue # 3 (sector line length).

This is the space to prepare a new proposal to the S101PT regarding the requirements and practical implementation of a new portrayal functionality aimed to extend the colored bands (sector arcs) of sector lights to follow the length of sector lines when either the nominal range (VNR) or the sector line length attribute value (SLL) are used.

**Comment by DavidGrant-NIWC** [comment]
# Extended sector arcs

S-52 conditional symbology procedure (CSP) LIGHTS06 continuation has a note:

> Note 2: When the mariner has selected that the sector lines be extended to the nominal range of the light, the manufacturer may offer the option of providing a second set of sector colour arcs in the extended coverage of the sector lines.

### Comparison of portrayal with and without extended arcs (click pics to enlarge)
|No extended arcs|With extended arcs|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/62906211/97886562-bd655780-1cf6-11eb-9ca3-1079d9d0708c.png)|![image](https://user-images.githubusercontent.com/62906211/97887096-6ca22e80-1cf7-11eb-9914-cc58557657be.png)|

## Question 1 - Should S-101 portray extended sector arcs?
- [ ] Yes
- [ ] No

* Situational awareness is enhanced when the end of the range is visible, at the cost of additional clutter.
* Underlying objects may be obscured.
* Does not help when the light and extended arc are offscreen.
* Note the mechanism for awareness of sector lights in ECDIS, per S-52 3.3.1.2:
    > Light sectors. It should be possible, on request, for the mariner to be capable of identifying the colour of the sectors affecting the ship, even if the lights involved are off the display.

## Question 2 - How to toggle display of extended arcs?
- [x] use a viewing group (our recommendation)
- [ ] use a context parameter

"_may offer the option_": I read this as a requirement that the extended arcs can be turned off. This could be accomplished through a viewing group or a context parameter.
* Recommend using a viewing group for consistency - this is how other aspects of the portrayal are shown or hidden.
* Context parameters are inefficient - changing any context parameter requires regenerating the portrayal prior to start of rendering.

## Question 3 - Viewing group assignment?
- [ ] 27071
- [ ] Other

* A new viewing group must be assigned to the extended arc so that it can be independently toggled on/off
* Lights, sector arcs, and sector lines are currently assigned to viewing group 27070

## Question 4 - What should the extended arcs look like?
- [ ] Match inner arcs
- [ ] Modified inner arcs
- [ ] Match sector lines
- [ ] Other

"_providing a second set of sector colour arcs_": I read this as indicating that the arcs should look like the primary arcs, and have colour.

|Match inner arcs|Modified inner arcs<br>(dashed, reduced line thickness)|Match sector lines<br>(no color, dashed)|
|:---:|:---:|:---:|
|![image](https://user-images.githubusercontent.com/62906211/97887096-6ca22e80-1cf7-11eb-9914-cc58557657be.png)|![image](https://user-images.githubusercontent.com/62906211/97891925-657e1f00-1cfd-11eb-98ad-dbee3f711658.png)|![image](https://user-images.githubusercontent.com/62906211/97892690-56e43780-1cfe-11eb-9fa9-b97c18bcb87d.png)|

# S-52 LIGHTS06 continuation:
![image](https://user-images.githubusercontent.com/62906211/97883210-8f7e1400-1cf2-11eb-9df1-d55a2fc5f2e3.png)

**Comment by alvarosanuy** [comment]
I disagree with the idea of displaying 2 sector arcs (default + extended). S-101 should modify the wording in S-52 to avoid this 'double vision' type of implementation.

I think there are merits to extend all sector arcs (including lights all around) at mariner's request. In many instances mariners simply want to cross check what they see with what they should be seeing (irrespective of the type of light).

**Comment by JeffWootton** [comment]
Agree with Alvaro's comment.

**Comment by TDYCARHugh** [comment]
The sector arc extension 'sector extension' attribute was added to S-101 (DCEG) as an additional portrayal attribute which was meant to simplify portrayal. This attribute was meant to avoid the loop through colocated lights and the logic to extend the smaller sector if sectors overlap.  In other words to set the 'extended arc radius' boolean instead of using a loop in the portrayal.
It would have been simpler if the  'sector extension' attribute had been defined as a boolean.  Having it as a random value introduces the concern for validation and special handling which defeats its original purpose to simplify portrayal logic.

The mention for manufacturers to offer an option to draw a second arc when the showing full length sector lines was meant to help the mariner figure out which is which when there are a lot of sector lines in the same area or when the actual light is off the screen.  Perhaps there are other mechanisms that could be explored for this situation such as a cursor pick listing of lights that should be visible at the pick location or other portrayal options.

**Comment by DavidGrant-NIWC** [comment]
Having a value allows for multiple overlaps - the portrayal logic is straightforward either way (value or boolean).

> The mention for manufacturers to offer an option to draw a second arc when the showing full length sector lines was meant to help the mariner figure out which is which when there are a lot of sector lines in the same area or when the actual light is off the screen. Perhaps there are other mechanisms that could be explored for this situation such as a cursor pick listing of lights that should be visible at the pick location or other portrayal options.
IMO this is helpful in the situations you describe, it's just a matter of resolving the issues noted above, or proposing other portrayal options.

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144343320-d7526a48-2e11-40e3-86f3-10297ba0bdf4.png)

**Comment by GuttormTomren** [comment]
IALA; 
This is the result/subset from Github #3. 
Rather technical, but conclusion is to draw arcs at radius 25mm (if desired by the mariner). It is also noted that the mariner should be able to be informed about color and sectors of lights outside his display window (when the ship is within nominal range of the light).

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 12/7/22**

1. Implement as per S-52 (20 & 25 mm). Sector Arc not to be extended to SLL or VNR for PC 1.1.0. Future proposals on this topic are to be submitted to an S101PT meeting for broader consultation and assessment.
2. DCEG subWG lead (JW) to amend section 30.4 to align with S-52 (use 5mm and not 3mm) - Change expected for S-101 1.1.0.
