### ISSUE TITLE
Masking of edges by portrayal rules

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#32]
The DCEG subWG has requested the Portrayal subWG to assess the possibility of automating the masking of feature edges (as recommended in DCEG 2.5.10) using portrayal rules instead of relaying in manual intervention.

**Comment by alvarosanuy** [comment]
My personal preliminary view is that, even if technically possible, some scenarios can't be automated and will still rely on human assessment and intervention. Having said that, some automation is better than none.

**Comment by DavidGrant-NIWC** [comment]
This is really asking for automated suppression: the suppression of edges during rendering/portrayal without use of masking information normally provided in the encoding.

# Summary
* Automation is not possible in all cases
* Where possible, would have a negative impact on portrayal performance
* I don't feel this is appropriate
  * Moves the burden from the (single) data encoder to the many data users
  * If desired, automation should be provided in the production software
    * Production software is not restricted by the S-100 model
    * Production software has all datasets available, portrayal only has access to a single dataset
    * Any performance penalties are paid only once, vice during every portrayal
    * Automated output of the production software can be validated prior to use

# Use cases (from S-101 DCEG 2.5.10 Masking)
* Area objects crossing ENC cell boundaries
![image](https://user-images.githubusercontent.com/62906211/130113702-ed7bf3a3-5bed-49cf-93de-2c31f1d89c63.png)
![image](https://user-images.githubusercontent.com/62906211/130113755-4f48ddbb-81d2-414f-b42c-65d925302f6d.png)
  * Portrayal can't tell if object continues across the boundary because it can only access information from a single dataset.
* Area objects having edges coincident with the coastline
![image](https://user-images.githubusercontent.com/62906211/130113791-7ec814f4-3272-44d6-babe-4f39441d8b1a.png)
  * Portrayal could detect co-incident geometries provided they share spatial components
* Area objects having ECDIS symbol pattern fill
![image](https://user-images.githubusercontent.com/62906211/130113846-1357f6bc-ea62-49fa-a051-73164d309414.png)
  * Suppress if there is no co-incident geometry with a shared spatial component?
* "Linear" area objects
![image](https://user-images.githubusercontent.com/62906211/130113894-e4e14f10-db05-462a-805e-d4d2fc0f21f5.png)
  * How to determine which is the line to keep?
  * Would likely require computing the area of all these objects and applying suppression if below threshold
* Routing measures - entrance and exit edges
  * Not considered

# S-100 Technical Issues
* Currently, masking information is provided in the encoding
  * Normally, the OEM rendering engine is responsible for suppressing portrayal of masked edges
    * Spatial and masking information is not provided to the portrayal
  * For drawing instructions which use augmented geometry, the portrayal must implement the suppression
    * Spatial and masking information must be made available to the portrayal if it is to be evaluated
    * There is currently no S-101 feature which outputs augmented geometry which requires suppression
* Many use cases can't be automated
* Even when possible, this would likely have a significant impact on the speed and memory usage of the portrayal
  * Features to be auto-masked would require spatial(s) to be available to portrayal for evaluation
    * Potential co-incident features would also need to be evaluated (e.g. the _DataCoverage_ surface)
    * The features would need to have at least one shared spatial component (e.g. to detect edges shared by a _DataCoverage_ and an _InformationArea_)
  * Masked features would need to output augmented or restricted geometries
    * Normally, a drawing instruction just references a feature and the OEM drawing engine evaluates the associated spatials
      * e.g. LineInstruction references an instance of CoastLine and provides a color, width, and line style
      * See 9-11.2.2 DrawingInstruction ![image](https://user-images.githubusercontent.com/62906211/130118556-3519d567-d1ce-401d-a6f8-e51a41dda8d4.png)

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144343941-15985d08-4e47-4dfd-9cad-50f35961faea.png)

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 13/7/22**

1. Discussions to clarify requirements are underway with the DCEG subWG. Close this issue and open new ones as needed once specific requirements are submitted by the DCEG subWG.
