### ISSUE TITLE
Current Non Gravitational - Portrayal of Surface and Curve geometry types

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#36]
Surface and Curve are new geometry types in S-101 (not used in S-57). Portrayal implementation is still pending.

- Discuss ideas on how these two new geometry types could be used to drive portrayal for features that cover a large geographic area using mandatory attributes **orientationValue** and **speedMaximum**.

- Discuss the feasibility of the technical implementation of the proposals.

**Comment by alvarosanuy** [comment]
In my mind Curves were introduced to facilitate the encoding of non gravitational currents which are usually captured in different sources as long and curvy lines (e.g. Gulf current). In this scenario, I believe the most appropriate display would be using 'current arrows' (CURENT01) tangent to the curve at predefined (TBD) distance intervals. The implementation of tangential orientations by the drawing instructions may be challenging or impossible but should be discussed. The other important element to consider with this implementation is that the encoding of **orientationValue** shouldn't be allowed for 'Curves' (orientation would be variable and would be the result of the tangential value it gets at a particular location on the curvy line). **speedMaximum** may not be required at each symbol, but not sure if technically possible to skip symbols (e.g. display only every 2 arrows).
In regards to Surfaces, I think the idea would be using a pattern of CURENT01 symbols oriented based on **orientationValue**. I think that a boundary line around the feature is not required. The display of **speedMaximum**, like for Curves, shouldn't happen at each arrow symbol.
In both cases (Curve and Surface), if **orientationValue** is populated with a Null value, we should use CURDEF01 symbols instead (horizontal display when north up ??).
**Also** - Is there any S-111 portrayal we could leverage on?

**Comment by DavidGrant-NIWC** [comment]
> [...] I believe the most appropriate display would be using 'current arrows' (CURENT01) tangent to the curve at predefined (TBD) distance intervals. The implementation of tangential orientations by the drawing instructions may be challenging or impossible but should be discussed. [...]

Symbols can be drawn similar to PIPSOL - interval between symbols must be in millimeters:
![image](https://user-images.githubusercontent.com/62906211/134687425-f8f01bb9-66df-406c-a2e6-fdc384610e1c.png)

> **speedMaximum** may not be required at each symbol, but not sure if technically possible to skip symbols (e.g. display only every 2 arrows).

Part 9 doesn't currently support placing text at repeated intervals along a curve. One of the following would be required:
* [ ] Update Part 9/9a to support this capability
* [ ] Place one or more labels individually on the curve.
  *  Multiple labels can cause clutter if the curve winds near itself.
  * If the curve winds on and off the screen the labels may not be visible.
  * Label placement can be affected by how the curves are encoded (e.g. one long curve will have a single label, the same curve encoded using 10 segments will have 10 labels).
  * If offsets in millimeters are used it is impossible to guarantee the entire curve will be labeled since the portrayal doesn't know how long each curve is
  * If offsets are in relative units (expressed as a percentage of the curve length) the labels will be bunched / cluttered on short segments and spaced far apart on long segments.
  * Most of these issues can already be seen with contour labels
* [ ] Incorporate the speed into the symbols portrayal via color, size scaling, or other method

> In regards to Surfaces, I think the idea would be using a pattern of CURENT01 symbols oriented based on **orientationValue**. I think that a boundary line around the feature is not required. The display of **speedMaximum**, like for Curves, shouldn't happen at each arrow symbol.

The Part 9 AreaFills package doesn't currently support text, so labels associated with the symbols of a SymbolFill instruction may be difficult to implement.

> Also - Is there any S-111 portrayal we could leverage on?

The prototype S-111 portrayal is using the 9-11.2.10 CoverageInstruction to draw an arrow at each discrete point of a Coverage: 
![image](https://user-images.githubusercontent.com/62906211/134706251-91a09571-b2c7-4448-82ca-6461978e2bdb.png)

**Comment by mikan66** [comment]
There is no S-111 portrayal.  That is my portrayal.
    On Friday, September 24, 2021, 12:13:38 PM EDT, DavidGrant-NIWC ***@***.***> wrote:  
 
 



[...] I believe the most appropriate display would be using 'current arrows' (CURENT01) tangent to the curve at predefined (TBD) distance intervals. The implementation of tangential orientations by the drawing instructions may be challenging or impossible but should be discussed. [...]


Symbols can be drawn similar to PIPSOL - interval between symbols must be in millimeters:



speedMaximum may not be required at each symbol, but not sure if technically possible to skip symbols (e.g. display only every 2 arrows).


Part 9 doesn't currently support placing text at repeated intervals along a curve. One of the following would be required:
   
   -  Update Part 9/9a to support this capability
   -  Place one or more labels individually on the curve.      
      - Multiple labels can cause clutter if the curve winds near itself.
      - If the curve winds on and off the screen the labels may not be visible.
      - Label placement can be affected by how the curves are encoded (e.g. one long curve will have a single label, the same curve encoded using 10 segments will have 10 labels).
      - If offsets in millimeters are used it is impossible to guarantee the entire curve will be labeled since the portrayal doesn't know how long each curve is
      - If offsets are in relative units (expressed as a percentage of the curve length) the labels will be bunched / cluttered on short segments and spaced far apart on long segments.
      - Most of these issues can already be seen with contour labels

   -  Incorporate the speed into the symbols portrayal via color, size scaling, or other method


In regards to Surfaces, I think the idea would be using a pattern of CURENT01 symbols oriented based on orientationValue. I think that a boundary line around the feature is not required. The display of speedMaximum, like for Curves, shouldn't happen at each arrow symbol.


The Part 9 AreaFills package doesn't currently support text, so labels associated with the symbols of a SymbolFill instruction may be difficult to implement.


Also - Is there any S-111 portrayal we could leverage on?


The prototype S-111 portrayal is using the 9-11.2.10 CoverageInstruction to draw an arrow at each discrete point of a Coverage:



—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DavidGrant-NIWC** [comment]
I said "prototype" 🙂


V/R,

David Grant
NIWC Atlantic 52400
(757) 541-5794 (w)
(312) 578-5794 (dsn)
(757) 708-4611 (m)



Disclaimer: I am not a contracting officer, authorized buyer, or other person authorized to make  contracts, purchases or business agreements of any kind. Requests for information or quotes do not constitute or imply a contract or other agreement of any kind.

________________________________
From: mikan66 ***@***.***>
Sent: Friday, September 24, 2021 1:47 PM
To: S-101-Portrayal-subWG/Working-Documents ***@***.***>
Cc: david.grant1 ***@***.***>; Comment ***@***.***>
Subject: [Non-DoD Source] Re: [S-101-Portrayal-subWG/Working-Documents] Current Non Gravitational - Portrayal of Surface and Curve geometry types (#36)


There is no S-111 portrayal.  That is my portrayal.
On Friday, September 24, 2021, 12:13:38 PM EDT, DavidGrant-NIWC ***@***.***> wrote:





[...] I believe the most appropriate display would be using 'current arrows' (CURENT01) tangent to the curve at predefined (TBD) distance intervals. The implementation of tangential orientations by the drawing instructions may be challenging or impossible but should be discussed. [...]


Symbols can be drawn similar to PIPSOL - interval between symbols must be in millimeters:



speedMaximum may not be required at each symbol, but not sure if technically possible to skip symbols (e.g. display only every 2 arrows).


Part 9 doesn't currently support placing text at repeated intervals along a curve. One of the following would be required:

- Update Part 9/9a to support this capability
- Place one or more labels individually on the curve.
- Multiple labels can cause clutter if the curve winds near itself.
- If the curve winds on and off the screen the labels may not be visible.
- Label placement can be affected by how the curves are encoded (e.g. one long curve will have a single label, the same curve encoded using 10 segments will have 10 labels).
- If offsets in millimeters are used it is impossible to guarantee the entire curve will be labeled since the portrayal doesn't know how long each curve is
- If offsets are in relative units (expressed as a percentage of the curve length) the labels will be bunched / cluttered on short segments and spaced far apart on long segments.
- Most of these issues can already be seen with contour labels

- Incorporate the speed into the symbols portrayal via color, size scaling, or other method


In regards to Surfaces, I think the idea would be using a pattern of CURENT01 symbols oriented based on orientationValue. I think that a boundary line around the feature is not required. The display of speedMaximum, like for Curves, shouldn't happen at each arrow symbol.


The Part 9 AreaFills package doesn't currently support text, so labels associated with the symbols of a SymbolFill instruction may be difficult to implement.


Also - Is there any S-111 portrayal we could leverage on?


The prototype S-111 portrayal is using the 9-11.2.10 CoverageInstruction to draw an arrow at each discrete point of a Coverage:



—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Fno-click.mil%2F%3Fhttps%3A%2F%2Fgithub.com%2FS-101-Portrayal-subWG%2FWorking-Documents%2Fissues%2F36%23issuecomment-926813140&data=04%7C01%7Cdavid.m.grant22.civ%40us.navy.mil%7C0de9b4e859434e3d0beb08d97f837a6c%7Ce3333e00c8774b87b6ad45e942de1750%7C0%7C0%7C637681024949692910%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nE7MYHjrQfSpwQmyLcUMu%2F2Yq%2B5ZdpTUQOPPX6oD9rU%3D&reserved=0>, or unsubscribe<https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Fno-click.mil%2F%3Fhttps%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAO756Y6UWRTDXD6L5UTNOKLUDS2UTANCNFSM5EVBLGSA&data=04%7C01%7Cdavid.m.grant22.civ%40us.navy.mil%7C0de9b4e859434e3d0beb08d97f837a6c%7Ce3333e00c8774b87b6ad45e942de1750%7C0%7C0%7C637681024949692910%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TqyTkBDYbNKxiDcwmYHrfQh%2BKsM8tJEyiEDwUHz9pT0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Fno-click.mil%2F%3Fhttps%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdavid.m.grant22.civ%40us.navy.mil%7C0de9b4e859434e3d0beb08d97f837a6c%7Ce3333e00c8774b87b6ad45e942de1750%7C0%7C0%7C637681024949692910%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=t2cFg9enq%2FU83OlCWY%2FLQIwQxLLjlh5%2Bak5QYNrzqNg%3D&reserved=0> or Android<https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Fno-click.mil%2F%3Fhttps%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdavid.m.grant22.civ%40us.navy.mil%7C0de9b4e859434e3d0beb08d97f837a6c%7Ce3333e00c8774b87b6ad45e942de1750%7C0%7C0%7C637681024949702903%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=eCifs1loNd8hvNFB5vLLRatc1jhiLPF3gzDdgi5t7sU%3D&reserved=0>.

**Comment by rmalyankar** [comment]
If curve geometry is required, that would involve a significant extension to S-111, because the S-100 HDF5 data format does not include curve geometry. It would require either extending the S-100 HDF5 format to encode vector geometry, or turning S-111 into a dual-format product (e.g., HDF5 plus GML files).  The issue of portraying curves with text at regular intervals would still remain. Also, the potential scope expansion for S-111 would obviously need to be put to the TWCWG chair team.

**Comment by Christian-Shom** [comment]
Is there a use case to illustrate "Curve" currents? If not, why should not restrict geometry primitive to point in S-101 ENCs?

**Comment by DavidGrant-NIWC** [comment]
Sub-wg agreed to recommend to DCEG that curve and surface geometries be removed.

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144344301-0abf6646-189c-485a-99d9-49b13db88ff6.png)

**Comment by alvarosanuy** [comment]
Curve and Surface geometric primitives options have been removed from the feature in DCEG 1.0.2.
