### ISSUE TITLE
Quality of Bathymetric Data and ECDIS Performance (Management of Temporal variation)

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#4]
**S-101PT5 Action 19** - Discuss paper S-101PT5-16

[S-101PT5_2020_16_EN_Quality of Bathymetric Data and ECDIS performance_V1.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5290004/S-101PT5_2020_16_EN_Quality.of.Bathymetric.Data.and.ECDIS.performance_V1.pdf)

This proposal requires:

- approval to introduce 2 new attributes **temporalValidity:** and **lowestQobdCategory**
- discussions over the implementation of a new boolean attribute **downgradeQobd** to allow HOs have control over the automated downgrading (or not) of QoBD by ECDIS (new proposal after informal conversations with some stakeholders).
- approval to add the proposed ECDIS performance to the 'S100 ECDIS performance' log for a post DF implementation
- approval to develop the proposed ECDIS functionalities and alarms to conduct preliminary testing (NIWC ?)

**Comment by DavidGrant-NIWC** [comment]
Sounding feature has the attributes shown below. It has an association to a pointSet, where each Z coordinate encodes the depth. Changes to a soundings attribute values affect all the associated points. Changes to the spatial associated with a sounding may affect individual points.

Need to clarify what should happen in the following cases:
- Feature
    - Add
    - Change an attribute value
    - Delete
- Spatial
    - Add one or more points
    - Move one or more points (x, y)
    - Modify depth (z)
    - Delete one or more points

**Sounding Attributes**:
![image](https://user-images.githubusercontent.com/62906211/95374112-ed623c00-08ab-11eb-92ef-aecc6f7cf261.png)

**Comment by Christian-Shom** [comment]
Approve the proposal. 
Information such as Temporal variation is useful but it will be efficient only if it is computed and portrayed as explained in the paper.
Of course, still needs to be tested, but this is the kind of improvements (among many others) that will make S-100 ECDIS more attractive.

**Comment by NLHO-Rogier** [comment]
Agree that S-101 should have an "expiry date" on the CATZOC (not using QoBD as the name change is under discussion at HSSC12). Automatic downgrading can be done two ways: 1) by the HO which then issues an update of an ENC OR 2) automatically within the ECDIS. Rather than a technical discussion, the liability should also be taken into consideration.
NLHO favors option 1.

**Comment by alvarosanuy** [comment]
![image](https://user-images.githubusercontent.com/70189016/97660576-22863680-1ac6-11eb-91b2-713d3d7e5860.png)

**Comment by NLHO-Rogier** [comment]
NL agrees to the introduction of the attribute temporal validity. NL does not agree to the automatic downgrading by ECDIS. This should be discussed as this will make a liability shift from the original ENC provided by the HO and the actual value used as determined by the ECDIS manufacturer.

**Comment by DavidGrant-NIWC** [comment]
> Agree that S-101 should have an "expiry date" on the CATZOC (not using QoBD as the name change is under discussion at HSSC12). Automatic downgrading can be done two ways: 1) by the HO which then issues an update of an ENC OR 2) automatically within the ECDIS. Rather than a technical discussion, the liability should also be taken into consideration.

### Option 1 (HO issues update)
Requires no changes to S-100, S-101, or ECDIS.

### Option 2 (Automated downgrading)
As I mentioned during the meeting, the method of downgrading as proposed in the paper is not consistent with S-100 portrayal. If automated downgrading based on date is desired then date dependent portrayal should be used. This would require the addition of a _fixedDateRange_ complex attribute to QoBD, with a multiplicity of 0..1.

If the _fixedDateRange_ is not present then the QoBD is always active. Otherwise the feature is only active during the indicated date range. If an end date is not encoded then the feature is active from the start date until the end of time. If a start date is not encoded then the feature is active from the beginning of time until the end date. 

If downgrading is desired, the HO would need to encode multiple QoBD features, one for each desired date range. Note that all of the features should reference the same spatial object, so the size of the encoding is not affected regardless of the number of date ranges.

> approval to introduce 2 new attributes _temporalValidity_ and _lowestQobdCategory_

Using date dependent portrayal obviates the need for the two proposed attributes. To support date dependent portrayal a _fixedDateRange_ complex attribute should be added with multiplicity 0..1.

> discussions over the implementation of a new boolean attribute _downgradeQobd_ to allow HOs have control over the automated downgrading (or not) of QoBD by ECDIS (new proposal after informal conversations with some stakeholders).

Using date dependent portrayal gives the HO full control over downgrading.

> approval to add the proposed ECDIS performance to the 'S100 ECDIS performance' log for a post DF implementation

Using date dependent portrayal requires no changes to ECDIS performance.

> approval to develop the proposed ECDIS functionalities and alarms to conduct preliminary testing (NIWC?)

We can support prototyping of proposed functionalities.

### Note on Alarms
Implementation of alarms triggered by QoBD is independent of the option selected; either method will support alarming on QoBD.

**Comment by Christian-Shom** [comment]
- FR approves to Retain the feature attribute categoryOfTemporalVariation from QoBD.
- FR approves Adding a new QoBD feature attribute (temporalValidity).
We not sure attribute temporalValidity should be mandatory.

**Comment by LARRIVEEJCANADA** [comment]
- CA Agree that S-101 should have an "expiry date" on the CATZOC.
- The Automatic downgrading should be done by HOs by issuing an update or an ENC for a question of liability. (Option 1)
- CA is not agree with Option 2 as this will make a liability shift from the original ENC provided by the HO and the actual value used as determined by the ECDIS manufacturer (same as Rogier).
-CA would like to know if this will be populated automatically (by S-57 to S-101 conversion) or this will have to be an extra coding for HOs on the S-101 side.  If so, should find an actual attribute in S-57 to code this and be able to switch automatically.  If this is not possible, this new attribute should not be mandatory.

**Comment by alvarosanuy** [comment]
Changes to the modelling of **QualityOfBathymetricData** feature have been introduced in DCEG 1.0.1 with the intention of facilitating testing options for the downgrading of QoBD. 

**DCEG 3.7.1** - [NOTE: The modelling of the complex attribute zone of confidence and accompanying encoding guidance 
in this Edition of S-101 Annex A is intended to allow for 2 options for the encoding of degrading bathymetric 
data quality over time for testing purposes. One of the options described must be used when encoding the 
quality of bathymetric data for an area. This modelling will be consolidated when the preferred option has 
been determined. See also clause 24.5.]

Currently awaiting implementation in FC and production tools to generate test data and conduct testing. Based on test results, modelling may require further changes.

**Comment by SylviaSpohn-BSH** [comment]
After consultation with our source management we have to add that the temporal variation is very difficult to supply for us as a HO because we have a patchwork of differently variable sea areas and a lot of dredged areas with maintained depths. It is too much effort for little benefit here in the North and Baltic Sea region.

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144327227-4c19503d-1fef-43fc-bb66-adb87dff480b.png)

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 13/7/22**

1. There is no need for additional portrayal requirements (will use existing CATZOC symbols). 
2. **Requires test data to support testing by NIWC**. Modelling options are now available in FC 1.0.2. **QoBD** portrayal should change based on ECDIS's date and the date values (end and start) in each instance of the **zoneOfConfidence** complex attribute encoded.

**Comment by DavidGrant-NIWC** [comment]
Still needs testing with real data; the below was "faked" within the portrayal.
* Selecting a viewing date range which spans the QoBD fixed date ranges will result in multiple CATZOC patterns being displayed.
    * ![image](https://user-images.githubusercontent.com/62906211/197054705-7865aedd-a23c-48c4-b314-14b02aeaf4ba.png)

* The date dependent symbol may be annoying and hard to associate with the QoBD feature. The mariner can turn it off via viewing group 31032.
    * ![image](https://user-images.githubusercontent.com/62906211/197053937-24008524-da7f-4c1b-8c71-6fd524c8b5a3.png)

#### Input QoBD zoneOfConfidence attributes and resulting portrayal
|categoryOfZoneOfConfidenceInData|fixedDateRange.dateStart|fixedDateRange.dateEnd|
|:---:|:---:|:---:|
|1||20211231|
|3|20220101|20221231|
|5|20230101||

|Selected Viewing Date|Portrayal (click to enlarge)|Remarks|
|:---:|:---:|:---|
|Jan 1, 2010|![ShoreECDIS 2022-10-20T202651Z](https://user-images.githubusercontent.com/62906211/197051536-fd6ce42c-d815-48f8-9b64-9bfa1e8e5338.png)|Applies to any date prior to 2022|
|Oct 20, 2022|![ShoreECDIS 2022-10-20T202702Z](https://user-images.githubusercontent.com/62906211/197051719-920ef6ee-c000-4d34-85fc-ff16cef20756.png)|Applies to any date in 2022|
|Jan 1, 2025|![ShoreECDIS 2022-10-20T202716Z](https://user-images.githubusercontent.com/62906211/197051838-aa129b5f-02f6-429f-aa6f-98bc9b101aa2.png)|Applies to any date after 2022
