### ISSUE TITLE
Speed Limit [Vessel Speed Limit] - Possible amendment to RESARE04 rule

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#43]
Used in **RestrictedAreaRegulatory** (DCEG 17.4).

_Speed is often limited inside harbours in order to prevent wakes. If it is required to encode this restriction, it must be done using a Restricted Area Navigational feature (see clause 17.8), with the attribute category of restricted area = 24 (no wake area) or restriction = 13 (no wake). If it is required to encode cases where the speed limit is known, it must be done using restriction = 27 (speed restricted), with the speed limit encoded using the complex attribute vessel speed limit, sub-attribute speed limit._

**For discussion:**
Proposal to amend CSP **RESARE04** to replace SY(CTNARE51) with Inland ENC symbol NMKREG06A when **categoryofRestrictedArea** = 24 (no wake area) OR **restriction** = 13 (no wake) AND **restriction** = 27 (speed restricted).
If technically possible (and when encoded), superimpose  **speedLimit** attribute value within NMKREG06A symbol or next to it.  If not, this information would be available to mariners via Pick report only.

![image](https://user-images.githubusercontent.com/70189016/142952450-e5dbe977-0db3-423d-8907-b8be3e820982.png)

Please note that the existing unit of measurement for S-401 (as shown in the Portrayal registry image) is km/h while the S-101 unit of measurement for **speedLimit** is Knots.

**Comment by TomRichardson6** [comment]
Generally support the proposal, although I observe that the Vienna Convention on Road Signs and Signals adopts a red circle and for users the reuse of symbols common to road signage may be more intuitive. These aren't adopted internationally.  https://en.wikipedia.org/wiki/Vienna_Convention_on_Road_Signs_and_Signals

S-4 430.2 currently refers to magenta text but given the significant use of magenta it seems a valid case to diverge from S-4, in consultation with NCWG. Given the red highlight used for alerts I'd suggest a requirement for this symbology that it is easily distinguishable from alerts highlights. 

Noting the differences in units suggest we consider raising the need to expand the complex attribute vessel speed limit to support units with the DCEG sub group However it may not be necessary to display units as well (clutter) (although S-4 does).

Just an observation that some popular apps provide this information and I think this supports the user need to be able to have this information available without a cursor pick. https://www.wakewatch.com/no-wake-zones

**Comment by S-100ExpertTeam** [comment]
[11. Vessel Speed Limit.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/7826689/11.Vessel.Speed.Limit.zip)

![image](https://user-images.githubusercontent.com/77085220/148497134-9700c82a-649f-4e4b-9697-46c8f69ab0c3.png)

**Comment by S-100ExpertTeam** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/osw/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/osw/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/osw/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/osw/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=KO style='tab-interval:40.0pt'>




Symbol Name | Vessel Speed Limit
-- | --
Symbol Explanation | Vessel Speed Limit
Look up table affected | Restricted Area Navigational
Pivot Point Column   Pivot Point Row | 0.00   0.00
Width of Bounding Box:   Height of Bounding Box: | 8.2   8.5
Symbol Size: |  
Symbol Colors: |  
Comments: | Line weight 0.32 mm
Examples on ENC: |  
References: |  




</body>

</html>

**Comment by KlasOstergren-SMA** [comment]
Support the intention to portrayal speed restricted areas. I the Swedish archipelagos, speed restriction with various maximum speed limits is common so portrayal of speed restriction will increase safety of navigation and help the mariner to comply with the regulations. However, since a speed restriction not in all cases exists by the purpose of avoiding wakes, I propose that the symbol should be displayed in all cases when restriction=27 and not only when restriction=27 is used in combination with restriction=13 or 24.

**Comment by IngaFjellanger** [comment]
We agree that we need a new symbol for Speed limit (e.g. SPEEDLIM). Perhaps we could depict speed limit value red colour to coincide with the symbol colour. However, a black text is better readable.  We suppose we don't need to add speed limit units since it is strictly defined as Knots. 
As regards the symbol’s drawing we’d increase line width to 0.64 since it is very important symbology. The example of .svg file has width = 7.2 and height = 7.5 instead of mentioned 8.2 and 8.5mm correspondingly. But we think it is more suitable size of the symbol.
We agree with Klas that symbol should be displayed in all cases when restriction=27 apply.

Questions. 
1. Should we draw the symbol SPEEDLIM if the vesselSpeedLimit/speedLimit attribute is unknown (<empty>)? If so, should we draw question mark into the symbol? 
2. vesselSpeedLimit attribute may have several instances in RestrictedAreaNavigational feature for different vessel classes. Which value should be depicted with the symbol in this case? We suggest to show minimum value of the speedLimit attributes and to draw additional symbol "i".

Suggestions:
![image](https://user-images.githubusercontent.com/70318960/170021756-cca0a7c8-4b92-4c94-a4a4-6b310baf12b6.png); ![image](https://user-images.githubusercontent.com/70318960/170021790-a03a36a0-d104-4bd0-be17-bace6e7292f8.png); ![image](https://user-images.githubusercontent.com/70318960/170021831-0a87c648-2dbd-4e96-bf5b-8cb446da16dc.png)

**Comment by SylviaSpohn-BSH** [comment]
Agree to take a symbol similar to the sign for inner waters (the left-hand version is possible). The number of the speed should be displayed and the unit, as knots is not common in some countries (if it is world-wide km/h, no unit is necessary).

**Comment by GuttormTomren** [comment]
IALA support having symbols/indicators for areas where speed restrictions apply. This might be coded as areas, where info can be found by pick report/or indicated by symbols.

**Comment by HolgerBothien** [comment]
A few comments, observations, and recommendations:

1. The proposed symbols can easily mistaken for danger highlights
2. It is important to note that in Inland ENCs the symbols are used for physical existing notice marks. The symbols itself do not contain the actual value. Only in the pick report the real graphic may be shown as an option.
3. In ENCs speed restriction are usually part of a restricted area.
**My recommendations:** 

1. Do not add a specific portrayal for the speed limit.
2. Leave it for the mariner to find it by picking.
3. Allow the OEM to make some smart implementations e.g. Showing the speed limit at the cursor or own ship position in a dedicated part of the UI or create warnings when a speed limit is ahead on the current route.

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 13/7/22**

1. No portrayal changes to RESARE04 when **restriction** = 27 (speed restricted).
2. Request S100WG to develop new ECDIS performance requirement to alert mariners when approaching or navigating within a **RestrictedAreaNavigational** where restriction=27 (speed restricted). Additionally, the information encoded in the complex attribute **vesselSpeedLimit** must be exposed to the mariner (by 'pick report' or other means).

**Comment by alvarosanuy** [comment]
This issue has been re opened until S-98 change proposal is submitted to the S-100WG.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 19/10/23**

The original problem was that **RESAREs** with **RESTRN** !=14 (ATBA) and **CATREA** != 28 (PSSA) would be mapped as **RestricteAreaNavigational** and they wouldn't trigger Alerts. In this scenario, mariners wouldn't have the opportunity to discover areas having 'speed restrictions' along their planned route.

Now that **RestrictedAreaRegulatory** and **Navigational** have been merged back into one feature (**RestricteArea**), those areas having **RESTRN**=27 (speed restricted) [or **categoryofRestrictedArea** = 24 (no wake area) OR **restriction** = 13 (no wake)] will trigger an Alert and therefore would be investigated by the user who will find out the type of restriction and other details as documented by the producer (i.e. speed limits, vessel type or size, etc).

CLOSE this issue.
