### ISSUE TITLE
Buoy New Danger Marking

### ISSUE THREAD

**Issue by yurigangkor** [S-101-Portrayal-subWG/Working-Documents#46]
[1. Buoy new danger marking.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8195999/1.Buoy.new.danger.marking.zip)
![Buoy New Danger Marking](https://user-images.githubusercontent.com/92765146/156994947-5d5136fa-482b-4dc0-a5c1-278645cf7d7e.GIF)

**Comment by TomRichardson6** [comment]
Two comments and one question on this proposed new symbol;

1. Suggest the colours should be vertical stripes rather than horizontal stripes to be consistent with the emergency wreck marking buoy.
2. Noting the use of the relevant topmark shape in other simplified symbols (safe water and cardinals) should the upright cross be added to further distinguish this from special marks noting the importance of this mark type (indicating a danger). 

Question will a paper chart like symbol be proposed separately?

**Comment by HolgerBothien** [comment]
Created a symbol for a virtual aid to navigation - new danger marking.
[New danger.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8395819/New.danger.zip)
Is there a symbol for a real object required too? Would prefer circle as it is inside the VATON12 symbol.
.

**Comment by DavidGrant-NIWC** [comment]
Added the virtual AtoN symbol to #59. A symbol still needs to be developed for feature BuoyNewDangerMarking

![image](https://user-images.githubusercontent.com/62906211/165328776-ac39c1da-60b1-4fc5-84c7-f60041513252.png)

**Comment by yurigangkor** [comment]
![BuoyNewDangerMarking](https://user-images.githubusercontent.com/92765146/167806576-36e71aed-f160-4cd1-9020-4e773eda31ba.JPG)
[#46_BuoyNewDangerMarking.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8668156/46_BuoyNewDangerMarking.zip)

**Comment by SylviaSpohn-BSH** [comment]
To distinguish from special marks the vertically blue/yellow divided cross topmark shape seem a good solution for the simplified symbology. Could the cross topmark for the traditional symbology be adapted a bit according the new shape?

**Comment by GuttormTomren** [comment]
IALA do not support this development or change in name. The current IALA Maritim Buoyage System (MBS)is pending approval at next year IALA Conference, the document is 99% completed and is sent from the working committees to IALA Council for consideration, just minor editorial changes are expected. Currently we have several defined marks, including a dedicated mark named EWMB, and this is not scheduled to change. This EWMB symbol might be be used (as indicated) for marking new dangers. In many cases this is used for wrecks, hence the name. The MBS also include a concept of marking new dangers, these might be of various nature, but they are not yet included in charts etc. (newly discovered). These might be marked with lateral, cardinal, isolated danger or the EWMB. If deemed necessary at least one of the marks should be duplicated. 

A wreck may well be a new danger, and could be marked with AtoN other than the EWMB but it is unlikely in the converse, that a more general new danger would be marked by the EWMB, for example a changed shoal area where specific direction to proceed is required.
IALA do not support the renaming of the EWMB to new danger mark, since other marks also are defined to be included for marking new dangers. 

Regarding the symbol, it is most important that the mark display in both yellow and blue color. This is the only mark with this combination. If the symbol is a sphere or square is less important.

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 12/7/22**

1. Update PC to link any instance of the **BuoyNewDangerMarking** feature to symbol 2022_BOYNDM01 as prepared by KHOA. The same symbol is to be used for _Simplified_ and _Traditional_ symbol sets.
2. DCEG subWG lead (JW) will liaise with IALA to discuss a possible name change to this feature (from **BuoyNewDangerMarking** to **EmergencyWreckMarkingBuoy**. This may impact on the name of the existing portrayal rule but not in the symbology to be used.

**Comment by TomRichardson6** [comment]
@alvarosanuy Noting my recent comment against the Portrayal Catalogue can you confirm that the intent is for this simplified symbol to be displayed even when paper chart presentation is selected by the mariner? This seems potentially confusing and inconsistent with the approach adopted in S-52. Currently in PC 1.1.2 this feature only ever displays with the simplified symbol.

**Comment by GuttormTomren** [comment]
See proposal for symbol EWMB github #117 document uploaded from Holger 23 May 2023. Suggest we use that symbol.

**Comment by TomRichardson6** [comment]
Thanks @GuttormTomren so as I understand it, because we expect to introduce the new colour filled buoy and beacon symbols a traditional paper chart symbol has not been created here. That's fine but I'm not sure an overall decision has yet been taken to adopt the colour filled symbols @alvarosanuy is this a decision that we could get the PT to take at PT11? It seems a logical improvement to me.

**Comment by alvarosanuy** [comment]
@TomRichardson6 - The PsWG has already approved and registration and mapping of the colored symbols for 1.2.0 (Issue https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/117 - Comment made on 11/5/23). I will add an slide on this in my report to S101PT11.
