### ISSUE TITLE
Vessel Traffic Service Area

### ISSUE THREAD

**Issue by yurigangkor** [S-101-Portrayal-subWG/Working-Documents#50]
[5. Vessel traffic service area.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8204305/5.Vessel.traffic.service.area.zip)
![Vessel Traffic Service Area](https://user-images.githubusercontent.com/92765146/157201688-57b516dd-5467-47ed-b76e-2254ed9f44a1.JPG)

**Comment by IngaFjellanger** [comment]
According to S-4 B488.3 the paper chart symbology of the VTS area must be presented as “a magenta dashed line (N1.2) with a legend in slopping magenta text along the inside of the line, for example ‘Severn VTS (see Note)’”
For S-52 presentation the line pattern ‘CTYARE51’ corresponds to the INT1 symbology N1.2. Consequently, it will be logical if we use the same pattern to depict limit of Vessel Traffic Service Area feature.
Actually, we have to create a new line pattern based on CTYARE51 and to include the symbol 'VTS'  between dashes like it is for DWRUTE51 pattern
![image](https://user-images.githubusercontent.com/70318960/170062881-25606b29-6682-4bef-9a3b-81d0a22d5b65.png)

Suggestion:
Add a new symbol EMVTSARE.svg.
Describe a new line pattern (e.g. VTSARE51) like the DWRUTE51 pattern where the symbol ‘EMVTSARE’ (VTS) is used instead of the symbol ‘EMDWRUT1’ (DW).
Modify the VesselTrafficServiceArea.lua to provide depiction of area limits by VTSARE51 line pattern. if the context parameter ‘Plain Boundary’ is ON, draw a simple dashed line with width 0.32 and colour: CHMGD.
Place a text with the feature's name with prefix 'VTS' into visible part of the Surface.

**Comment by LeoKuzmin** [comment]
Here are files that are necessary for VTS area portrayal.
[VTS_Portrayal.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9094279/VTS_Portrayal.zip)

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 12/7/22**

1. Update rule to link **VesselTrafficServiceArea** feature as per the instructions following bullet point 2 below (_Simplified_ and _Traditional_ symbology + use of **featureName**):

2. @IngaFjellanger to add SVG, CSS and Engineering Drawing files to this Github issue for inclusion in PC 1.1.0.

> According to S-4 B488.3 the paper chart symbology of the VTS area must be presented as “a magenta dashed line (N1.2) with a legend in slopping magenta text along the inside of the line, for example ‘Severn VTS (see Note)’” For S-52 presentation the line pattern ‘CTYARE51’ corresponds to the INT1 symbology N1.2. Consequently, it will be logical if we use the same pattern to depict limit of Vessel Traffic Service Area feature. Actually, we have to create a new line pattern based on CTYARE51 and to include the symbol 'VTS' between dashes like it is for DWRUTE51 pattern ![image](https://user-images.githubusercontent.com/70318960/170062881-25606b29-6682-4bef-9a3b-81d0a22d5b65.png)
> 
> Suggestion: Add a new symbol EMVTSARE.svg. Describe a new line pattern (e.g. VTSARE51) like the DWRUTE51 pattern where the symbol ‘EMVTSARE’ (VTS) is used instead of the symbol ‘EMDWRUT1’ (DW). Modify the VesselTrafficServiceArea.lua to provide depiction of area limits by VTSARE51 line pattern. if the context parameter ‘Plain Boundary’ is ON, draw a simple dashed line with width 0.32 and colour: CHMGD. Place a text with the feature's name with prefix 'VTS' into visible part of the Surface.

**Comment by IngaFjellanger** [comment]
[Vessel.traffic.service.area.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9198195/Vessel.traffic.service.area.zip)
Here is the zip file with all the requested files

**Comment by mikan66** [comment]
See commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/5e1907aa3fd90df3551cb9f58808a39efdec5a91.
