### ISSUE TITLE
Anchorage areas

### ISSUE THREAD

**Issue by yurigangkor** [S-101-Portrayal-subWG/Working-Documents#56]
[13. Anchorage areas.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8204350/13.Anchorage.areas.zip)
![Anchorage areas](https://user-images.githubusercontent.com/92765146/157202625-03e8993f-92c4-49a4-a689-3415ef102d3b.JPG)

**Comment by yurigangkor** [comment]
![AnchorageArea](https://user-images.githubusercontent.com/92765146/167807298-f16d7266-45ba-4126-8c7f-36e458fd7c44.JPG)
[#56_AnchorageArea.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8668205/56_AnchorageArea.zip)

[KHOA] The top margenta line was cut off so the revised version has been uploaded.

**Comment by IngaFjellanger** [comment]
Do we need to create a new symbol (2021_EMACHAR2) with an upside down anchor? This symbol is intended just to be used in a new line pattern (2021_ACHARE51) for curves where Anchorage Area features adjoin. According to S-100 Ed.4.0 the clause 9-12.4.1.4. there is special tag which provides rotation of a symbol in a line pattern. For example:
   <symbol reference="EMACHAR1">
      <position>37.4</position>
      <rotation>180</rotation>
   </symbol>

Suggestion: 
Use the <rotation/> tag in a new line pattern for curves where Anchorage Area features adjoin.
Rename a new line pattern ACHARE61 instead of 2021_ACHARE51

**Comment by DavidGrant-NIWC** [comment]
Not sure that this symbol is necessary - see https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/8

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 26/7/22** This issue is related to https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/56

1. Submit S-98 change proposal to S-100WG with the aim of standardising the portrayal of shared edges by OEMs.
    **NIWC** to prepare draft proposal including the concepts listed in this github issue: 'dash alignment', 'symbol alignment' and 'symbol offset' . Change proposal to include images to facilitate interpretation by OEMs. Draft to be included in a new Github issue to be created by Alvaro (https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/100) to facilitate discussions and finalisation before submission to S100WG. 

2. The resolution of this issue is not required for PC 1.0.2 or 1.1.0. Close Issues 8 & 56.
