### ISSUE TITLE
NIWC Testbed Update - Slide # 16 - Portrayal of shared edges

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#8]
**S-101PT5 Action 24** - Discuss paper S-101PT5-21

[S-101PT5_21_EN_NIWC Test Bed Report_S101PT5_V1.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5290033/S-101PT5_21_EN_NIWC.Test.Bed.Report_S101PT5_V1.pdf)

![image](https://user-images.githubusercontent.com/70189016/94632862-09476a00-030f-11eb-9c9e-a18e97b7014d.png)

**Comment by alvarosanuy** [comment]
S-98 Annex C section C-8.2.9
As per S-52 (10.3.4.1), display priority followed by geometry type is indicated but no specific guidance is provided on how  to resolve instances where symbolised edges shared a spatial. It has been left open to OEMs (arbitrary decision).

"The display priority applies irrespective of whether an object is a point, line or area. If the display priority is equal among objects, line objects have to be drawn on top of area objects whereas point objects have to be drawn on top of both. If the display priority is still equal among objects of the same type of geometry (area, line or point) **the given sequence in the data structure of the SENC, or some other neutral criterion, must be used for an arbitrary decision as to which object is drawn on top**.''

Is there a way to standardize a solution? If there is, it should probably be documented.

**Comment by DavidGrant-NIWC** [comment]
The display priority (stacking / drawing order) does not matter - if both lines are drawn then the issue can occur. Line suppression cannot apply since the drawing priority is the same for both lines.

> ![image](https://user-images.githubusercontent.com/62906211/95874975-7d3a3700-0d3f-11eb-93d6-a67a17f056c7.png)

**Comment by Christian-Shom** [comment]
Geomod suggests adding in S-101 something like:
-   If two curve features, or two surface boundaries, or a curve and a surface boundary, are coincident, and those edges share the same line symbolization, only one curve should be symbolized.

**Comment by TDYCARHugh** [comment]
In S-52 and in S-100 it is up to the display system to implement suppression of drawing instructions on the same curve based on priority. In S-52 it stated that at the same priority all instructions would be applied.  In S-100 it does not give such guidance.
However in S-100 it is possible to assign instructions to specific curves using the optional spatialReference element of the Drawing Instruction.  So an S-100 portrayal could be designed to evaluate what features are sharing a curve and apply only the appropriate drawing instructions to those specific curves.
For example the portrayal rules for features such as anchorage areas could be designed to test for other anchorage areas sharing boundary curves and assign portrayal to those curves as desired.

I recommend that we limit suppression of portrayal to cases where curves are shared and not use conditions such as 'coincident' as this infers duplicate geometries and use of spatial operators which can have a significant negative impact on performance and cost of implementation as well as variances due to implementation of the operators/tolerances etc.  If the suppression of shared curves is important to a product spec then the product spec should define that coincident linear geometries must be shared.

**Comment by DavidGrant-NIWC** [comment]
> If two curve features, or two surface boundaries, or a curve and a surface boundary, are coincident, and those edges share the same line symbolization, only one curve should be symbolized.

This change would incorrectly symbolize areas outlined with complex line styles - e.g. anchorages which share an edge would only show the anchors oriented towards one of the anchorages.

We support Hugh's recommendation - we could prototype the recommendation and report results.

**Comment by TDYCARHugh** [comment]
You may wish to have a new linestyle that has anchor symbols in both directions which would be used on curves shared by anchorages on either side.

**Comment by rmalyankar** [comment]
Or, more generally, an algorithm for merging linestyles?

**Comment by DavidGrant-NIWC** [comment]
> You may wish to have a new linestyle that has anchor symbols in both directions which would be used on curves shared by anchorages on either side.

This is also a great idea as it could really help reduce clutter when there are large numbers of anchorages and restricted areas.

![image](https://user-images.githubusercontent.com/62906211/96034432-8a365380-0e2f-11eb-908c-ea6c596a9770.png)

**Comment by DavidGrant-NIWC** [comment]
## Summary
* No change to the portrayal catalogue is needed to address this issue
  * As suggested by Holger, this can be addressed during post-processing (while evaluating line suppression).
* Group should decide if they want to recommend addressing within S-98
  * Recommend or require dash and/or symbol alignment.
  * Since no change to S-101 is required, recommend closing this item once decision is made.
* NIWC test bed will implement both dash and symbol alignment.

## Investigation / Testing
### Dash patterns
* Issue is present in S-64 so it affects at least some existing systems.
**From S-64**:
![Screenshot 2021-11-08 100037](https://user-images.githubusercontent.com/62906211/141506996-537388e2-7c35-4b54-9c62-5aed699015c5.png)

* As suggested by Holger, dash patterns can be aligned in post processing with no change to portrayal. This can be done while evaluating line suppression. Here's a couple of examples of dash alignment. In my opinion this better reflects the intended portrayal:
**Testbed showing S-164 dataset**:
![Screenshot 2021-11-08 100027](https://user-images.githubusercontent.com/62906211/141507134-b1b71aac-4868-4242-8d84-6421fbc2224a.png)
**Testbed showing area from original issue report**:
![ShoreECDIS 2021-11-08T144740Z](https://user-images.githubusercontent.com/62906211/141507467-e7783383-7d75-4c8f-b1a7-dddf89a105dd.png)

_Note: Implementing dash alignment can result in a dash spacing which differs from that specified by the drawing instruction. This can occur for the space between two dashes on either side of  the vertex separating one curve geometry from another. In my opinion, this is a reasonable trade-off for the benefit provided. A more advanced algorithm could distribute the error along the length of the curve (provided the curve is long enough)._

### Symbol patterns
* It's also possible to align symbols when they share a common symbol and spacing interval (most commonly occurs when two instances of a feature type with surface geometry share a common boundary).

**Testbed showing anchorages with symbol alignment**:
|Portrayal|Pick report on outer anchorage|Pick report on inner anchorage|
|:---:|:---:|:---:|
|![ShoreECDIS 2021-11-08T150235Z](https://user-images.githubusercontent.com/62906211/141510277-d1415279-a33b-45f5-81f9-26f30a701442.png)|![ShoreECDIS 2021-11-08T150254Z](https://user-images.githubusercontent.com/62906211/141510181-3e0cb342-a83d-4f00-8206-5675683c7f9e.png)|![ShoreECDIS 2021-11-08T150301Z](https://user-images.githubusercontent.com/62906211/141510190-7f32f631-5034-41c8-ad28-5189e37bb780.png)|

**Examples comparing use of alignment**:
|Without Alignment|With Alignment|
|:---:|:---:|
|![ShoreECDIS 2021-11-06T041334Z](https://user-images.githubusercontent.com/62906211/141509188-6427da94-5dd0-4442-b588-652f8b0d689b.png)|![ShoreECDIS 2021-11-06T041252Z](https://user-images.githubusercontent.com/62906211/141509211-969ae646-1388-42c8-b030-b9e516bcb11a.png)|
|![ShoreECDIS 2021-11-06T033116Z](https://user-images.githubusercontent.com/62906211/141509639-5fe57336-cc4c-4716-a5d1-fe6258b01450.png)|![ShoreECDIS 2021-11-06T033040Z](https://user-images.githubusercontent.com/62906211/141509695-256d6211-6bcc-4dea-84e5-928a2d92ce88.png)|
|![ShoreECDIS 2021-11-06T040610Z](https://user-images.githubusercontent.com/62906211/141509952-bed9ecc5-43bb-4425-bc67-f45a459ccdf4.png)|![ShoreECDIS 2021-11-06T040641Z](https://user-images.githubusercontent.com/62906211/141509958-ec15dbc0-a2ac-418f-ab1f-1d7ca1072077.png)|

**Comment by alvarosanuy** [comment]
Hi Dave,
Just to clarify as I am finishing the decisions and actions from our last meeting; do you need somebody to develop a new SVG line style for Anchorage Areas (alternating pattern of anchor symbols pointing into opposite directions)?
If the answer is no, then I will close this Guithub issue and document that the subWG preference is to manage overlapping dash & symbol patterns, **for adjoining features of the same type**, by aligning them in post processing, with no change to portrayal. This would be done by the ECDIS while evaluating line suppression.

**I believe this processing shouldn't be optional and that it should become an ECDIS performance requirement. If the rest of the group supports this, I'll add an action to submit a change proposal to S-98.**

- [ ] PLEASE let me know your views ASAP.

**Comment by MikusRL** [comment]
Looking at the examples above I personally have two way reaction: One is that the simple dashed lines portrayal is solved and should be proposed to solve documentation wise as Alvaro recommends. the other thought is cautious, as when the anchorage or Resare symbology is unlined, it is messy, but at some parts at least could be "read" and interpreted as originally intended. Meaning - mariner lookin gat "messy" line is cautions and puts extra effort in to "read" this - safe side of data interpretation. But when it gets aligned, it becomes clear and consistent, forming another symbol, which "as combined" might loose its original intention - mariner could misinterpret it and not try to learn what this line represents and potentially miss some important data interpretation. I would suggest to consider to recommend this action only for simple dashed line. Or for all lines, but with the caveat, that newly combined variations, creating new symbols on screen, needs to be included in ECDIS Chart1 with explanation what the combined new symbols mean and how to translate them. Just a suggestion for considering.

**Comment by DavidGrant-NIWC** [comment]
> do you need somebody to develop a new SVG line style for Anchorage Areas

My opinion is that it's not necessary. I feel like aligning the existing symbols gives a similar effect.

> [require alignment] for adjoining features of the same type

The requirement should be for matching spacing. There are dash patterns and symbols that can be aligned that aren't necessarily for the same feature type, and don't use all of the same symbols. A notional example: "dash dot dash" and "dash space dash". A real example is caution area and anchorage area, which both share the same symbol spacing so their symbols can be aligned (the triangles are shared in both patterns, while the caution uses a "!" symbol where the anchorage uses an anchor symbol): 
![image](https://user-images.githubusercontent.com/62906211/141710697-94e2130f-3734-41cb-9665-9cc84ee16ead.png)

> as when the anchorage or Resare symbology is unlined, it is messy, but at some parts at least could be "read" and interpreted as originally intended

Bear in mind that the symbols can be aligned by accident, so there is no guarantee what the symbols will look like when no attempt is made to synchronize the patterns. Also, the pick report should clarify the situation and as the mariners become familiar they will recognize the common combinations. The use of "plain boundaries" should also be taken into consideration (all "symbolized" line styles become solid or dash patterns).

One option to further modify the appearance would be to offset the symbols from the center of the line when they would intersect one another, but this could cause it's own issues which should be investigated prior to recommending (might make the location of the line less obvious for some feature types, could cause clutter for small areas, etc.):
![image](https://user-images.githubusercontent.com/62906211/141714550-74e31181-57fd-4332-8ebd-422d4b63d064.png)

![image](https://user-images.githubusercontent.com/62906211/141714389-bf3bfbbc-a334-47c2-87ae-ab66dd8dd740.png)

**Comment by MikusRL** [comment]
Great job there in testing! Although you mentioned the potential issues could arise on the cluttering in small areas, but I think that offsetting the symbols make a lot of sense and would propose to test this further for the "potential issues". Maybe it is possible and feasible to reduce the offset symbol size, say by 20%. Would need testing, and am not sure if it is allowable in ECDIS standard. And I acknowledge the test data necessity then. I can not promise, but will try to find if we have any examples with small areas sharing edges.
Regarding the "...and as the mariners become familiar they will recognize the common combinations....". I understand and that was the way forward when it was at the frozen standard way, but now I believe that we are at the point where we can improve portray and standards for the benefit to the end user not to complicate their experience and possible human error minimization, so I would like to see that as a "second" option, if we have reached our limits of solutions here.
But of course open to the other group members to express their views.

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144341783-a9c2f5e1-d684-46d2-994e-46d0bf0e4efd.png)

**Comment by LeoKuzmin** [comment]
Based on our experience we could offer the option where shared curve use combined line styles depending on feature type and/or their attributes. For example, we add a line style for adjoined Anchorage Areas - ACHARE61 
![image](https://user-images.githubusercontent.com/106175259/171029696-b0e2738e-7450-4088-a3f7-bdb9410dd0fe.png)
Please, pay attention, that we don't need additional symbol, enough to use `<rotation>180</rotation>` tag in the xml file for the second symbol.
The modified AnchorageArea.lua script checks adjoined features AnchorageArea  on a shared curve.
If curve is referenced with different directions from adjoined features, the script depicts the combined like style. If the direction coincide the ordinary ACHARE51 line style is used. 
![image](https://user-images.githubusercontent.com/106175259/171032974-26496096-1b29-4233-afbb-3645a0e84d5f.png)
There are like situations with restriction areas, for example:
![image](https://user-images.githubusercontent.com/106175259/171033752-25f863af-ba92-45ee-9a11-35070c76c346.png)

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 26/7/22** This issue is related to https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/56

1. Submit S-98 change proposal to S-100WG with the aim of standardising the portrayal of shared edges by OEMs.
    **NIWC** to prepare draft proposal including the concepts listed in this github issue: 'dash alignment', 'symbol alignment' and 'symbol offset' . Change proposal to include images to facilitate interpretation by OEMs. Draft to be included in a new Github issue to be created by Alvaro (https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/100) to facilitate discussions and finalisation before submission to S100WG. 

2. The resolution of this issue is not required for PC 1.0.2 or 1.1.0. Close Issues 8 & 56.

**Comment by DavidGrant-NIWC** [comment]
S-98 Annex C change proposal:

![image](https://user-images.githubusercontent.com/62906211/200029002-b3684f11-37fd-4dd5-8a64-7a08282d8182.png)
[S-98 Standardization of the portrayal of shared edges in ECDIS.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9941369/S-98.Standardization.of.the.portrayal.of.shared.edges.in.ECDIS.pdf)
