### ISSUE TITLE
No Geometry Feature: Range System (RangeSystem)

### ISSUE THREAD

**Issue by mikan66** [S-101-Portrayal-subWG/Working-Documents#85]
A rule is needed to define portrayal for this feature which has permittedPrimitives defined as "noGeometry".
Alias: C_AGGR

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 26/7/22**

1. **Jeff** to take the discussion to the DCEG subWG to ensure there's a way to enable the portrayal of **featureName** when encoded in features with 'no geometry' (change in modelling or encoding guidance). The decisions would impact on all features listed in Github issues 80 - 87.
2. S-98 probably requires some additional instructions on how to expose this information by 'pick report', but to be discussed once DCEG discussions are finalized.
3. Leave issue open until outcome from DCEG subWG discussions.
4. Not for 1.0.2.

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 12th January 2023**

1. Implement text instruction for when **featureName** is set to 'display'

**Comment by mikan66** [comment]
@alvarosanuy, please provide viewing group and radar info for "Range System" to complete portrayal for S-101.

**Comment by alvarosanuy** [comment]
> @alvarosanuy, please provide viewing group and radar info for "Range System" to complete portrayal for S-101.

- [ ] **Standard display - VG=27220 (needs registration in the GI Registry)

- [ ] **Over-radar**

**Other views???**

**Comment by MikusRL** [comment]
For the viewing group and Radar - to my understanding it should be in the same group as other texts and labels for AtoNs, Recommended Route Centerline, Navigation Line and Recommended Track, as the text does not make sense if the other objects are not visible - DCEG 15.6.1. 

Could you please remind where I could see the viewing groups listed and what is with those already registered? Thanks. My apologies if I did asked already earlier and did forgot.

**Comment by alvarosanuy** [comment]
> Could you please remind where I could see the viewing groups listed and what is with those already registered?

**S-98 Annex C - C-9.5**

It seems that the VG that have 'na' next to them have not been registered in the GI Registry.

**Comment by DavidGrant-NIWC** [comment]
See also S-98 Annex C, clause C-11 which contains the viewing groups and viewing group layers used for text. Text is assigned to viewing groups from 0 through 99. There are two viewing group layers for text, and these layers are not part of a display category - meaning that text can always be toggled on/off regardless of the ECDIS selected display category (Base/Standard/All Other).

When portraying text, the PC rules generally assign multiple viewing groups to the text instruction. The text has its own viewing group which allows the text to be toggled on/off independently of the labeled object. The text also uses the viewing group of the labeled object, which ensures the text turns off whenever the labeled object is turned off.

For instance, when labeling _TrafficSeparationSchemeLanePart_ the label has two viewing groups: 24 (the viewing group of the text) and 25010 (the viewing group of the object to which the label applies - the TSS). Both viewing groups must be enabled for the text to be visible. If either is disabled, the text will not be visible. The text will never be visible in the **Base** display category because the TSS is not visible in the **Base** display category.

Also, text always has a drawing priority of 24 (0-27 scale). I can't find a requirement for the display plane assigned to text, so I assume it inherits the display plane from the labeled object.

**Comment by alvarosanuy** [comment]
Implemented in PC 1.1.0
