### ISSUE TITLE
Incorrect drawing of some Complex line styles - Part 2

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#90]
**Dedicated Github issue to discuss topic presented by dKart (@IngaFjellanger) in the paper below (bullet point 8):**

[Comments to Portrayal Catalogue_last version.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9193818/Comments.to.Portrayal.Catalogue_last.version.docx)

Extract from paper:

8.	Linear patterns for example: CHRVDEL2, LOWACC31 and LOWACC41 have unnecessary solid lines under pattern’s symbols. Those lines create cluttering and unreadable patterns. They should be removed.
The reason of it is the usage of the actual value (e.g. 0.32) of the width attribute in the pen tag. According to the clause 9 – 12.4 The LineStyle package of the S-100 Ed.4 the Pen element is mandatory for a LineStyle. We cannot remove it if we need just to draw a sentence of symbols. We can however assign the width attribute equal to ‘0’.

**Comment by alvarosanuy** [comment]
**Initial comment provided by Hugh on 27/7/22:**

_I traced through the conversion of each and found the following._

**LOWACC21** – Reported Problem: a thin line is being drawn under the pattern.
**Assessment**: The line style does not include a line drawing instruction.  Perhaps the programmers have misinterpreted the linestyle instructions.  I have some notes I can add to the github issue

**Comment by IngaFjellanger** [comment]
Here is how we see it
![unnecessary_solid_lines](https://user-images.githubusercontent.com/70318960/181209131-8632c81a-a0de-4281-b1d9-0f279762eec3.png)
:

**Comment by IngaFjellanger** [comment]
Here is how we have amended the presentation:
[needlessSolidLine_comment#8.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9196814/needlessSolidLine_comment.8.zip)
Note that the header is not up to date

**Comment by TDYCARHugh** [comment]
In the S-100 Linestyle the pen element is mandatory.  It is my understanding that the pen element is not used for anything unless there is a dash instruction.  If you want to have a solid line under the symbols within the linestyle then there would be a dash instruction starting at 0 and going to the length of the interval value.  Since there is no dash instruction there should not be a solid line.

A better way to make a solid line or std dash with symbols on top would be to have two drawing instructions, a simple linestyle followed by a complex linestyle with the symbols.

The pen element is meant to define the colour and width of the pen. It is not a drawing command.

Conclusion: these linestyles don't need to be changed.

**Comment by DavidGrant-NIWC** [comment]
Agree with Hugh that this is not an S-101 issue - our test bed implementation matches what Hugh describes. However, I can see that the model might be confusing.

Note S-100 9-11.1.9 says details are provided in the LineStyles package, but _9-12.4 The LineStyles package_ only provides the model without further explanation other than descriptions of the attributes.

Descriptions
* LineStyle: A style for line geometry either solid or dashed
_[Implies lines always have either a solid or dashed component]_
* _intervalLength_: The length of a repeating interval of the line style [...] If not defined the line style describes a solid line.
_[LineStyles without intervalLength are not always solid lines, it depends on the presence of a _dash_ attribute]_
* _dash_: The dashes of a dashed line style
_[Missing a note: If the dash attribute is not present then only the symbol components should be drawn, a solid line should not be drawn]_

Recommend we submit a change proposal to change the multiplicity of pen from 1 to 0..1 and to update the descriptions.

![image](https://user-images.githubusercontent.com/62906211/181274620-6d9b6539-a041-4d86-98c7-9b2ad55ada36.png)

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 12th January 2023**

1. **NIWC** to submit Clarification proposal to S100WG.

2. Close this issue when the proposal is submitted.

**Comment by DavidGrant-NIWC** [comment]
Submitted to TSM9, will submit to S-100WG8 assuming no objections.

Since this is a clarification I didn't change the multiplicity of the pen attribute, I just updated the attribute descriptions.

[Clarification for Part 9 LineStyle.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/10885437/Clarification.for.Part.9.LineStyle.pdf)

**Comment by alvarosanuy** [comment]
@DavidGrant-NIWC - Can we close this issue?

**Comment by DavidGrant-NIWC** [comment]
Yes, the proposal has been submitted for WG8
