### ISSUE TITLE
Sounding Approximate

### ISSUE THREAD

**Issue by Christian-Shom** [S-101-Portrayal-subWG/Working-Documents#95]
From ENCWG "Display Sub WG"
The use of a circle around approximate sounding increases clutter and can be confused with a depth contour. 
![image](https://user-images.githubusercontent.com/71139640/181247380-44b1c28b-6ca4-457e-94a8-4588739bf450.png)
The portrayal could be improved in S-101, although that may create a disruption with S-57 ENC presentation.

**Comment by alvarosanuy** [comment]
The 'circle' [_SY(SOUNDGC2) & SY(SOUNDSC2)_] around soundings is triggered by a number of different attribute values.
Summary is listed below but refer to CSP SNDFRM04:

STATUS=18
QUASOU=2 or 3 or 4 or 5 or 8 or 9
QUAPOS=2 or 3 or 4 or 5 or 6 or 7 or 8 or 9

The 'blanket' effect on ENC is usually caused by the over encoding of:

- **QUAPOS=4** (_PA_) - Most likely due to legacy PC to ENC conversion issues where paper charts showed numerous upright soundings (INT1 I14). Upright soundings in PCs should, according to S-4, reflect 'unreliable soundings' which, according to the UOC, are those soundings that are less reliable (lower ZOC) than the charted CATZOC value (M_QUAL) for the area (i.e. a ZOC C sounding that couldn't be disproved by a new CATZOC B survey and had to be retained due to its depth). In short, encoding guidance should state that when all soundings are from the same ZOC (or higher) none of them should be encoded with QUAPOS=4, even if they are all ZOC D or a bad ZOC C. In the example, **only** the ZOC C sounding should be encoded, as 'unreliable' (QUAPOS=4 and QUASOU=4 as per the UOC) and therefore display the 'circle' around it. The quality and reliability of the charted depths in ENC is now informed by M_QUAL (i.e. if the ZOC=D, you do not need circles around the soundings to know their values/positions/sea bottom coverage is bad). S-57 to INT1 mapping rules can help with keeping PC symbology if desired ....... (i.e. soundings within ZOC D areas must come upright when migrated to INT1).

- **QUASOU=5** (_NBA_) - Not sure why INT1 symbol I13 was not migrated to S-52. We could explore bringing it back and/or amend the UOC and direct encoders to capture SWPARE when the NBA area is extensive (i.e. common output from LIDAR surveys nowadays).

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 12th January 2023**

1. The subWG decided to refer proposals to update existing symbology or develop new one to the NCWG. This is to provide an opportunity to harmonise presentation among different charting products and ensure concepts and definitions between S-4 and DCEG stay aligned.

2. **Alvaro** to submit this issue for discussion at the next NCWG meeting in November 2023. Issue will remain open until feedback is received by the NCWG.

3. @JeffWootton - Possible discussion point for the DCEG subWG (refer to my comment regarding AHO's  encoding practice above).

**Comment by alvarosanuy** [comment]
Paper submitted to NCWG9 (Nov 2023).
Will leave this issue open until we get feedback from NCWG Chair.

**Comment by MatthewCraggs** [comment]
### Below are the comments from NCWG9.

The circles drawn around poor-quality soundings in an ENC can be mistaken for depth contours and the 
depiction is confusing. 

**_Outcome:_** NCWG recommends retain the circles as that is what the user is now used to interpret. 
Clarification in the encoding guidance to ensure consistent use could be a benefit.

**Comment by alvarosanuy** [comment]
NCWG has decided not to amend symbology at this point in time.
