### ISSUE TITLE
Depth contour values

### ISSUE THREAD

**Issue by Christian-Shom** [S-101-Portrayal-subWG/Working-Documents#97]
From ENCWG "Display Sub WG"
Too many values shown on the ECDIS.
![image](https://user-images.githubusercontent.com/71139640/181249135-01847e69-ee10-4e44-a36f-8e3e0ae6013d.png)
Although this seems to be an ECDIS issue, interesting to look if some guidance or portrayal rule can be added somewhere.

**Comment by DavidGrant-NIWC** [comment]
The current S-101 portrayal places a label half-way along the contour.

This is not ideal (because the label position may not be on the screen, or the curve may be long and winding so that the label is hard to associate with a particular segment), but the Part 9 model limits what is possible with regard to text placement associated with curves. Ideally, we would extend the model to at minimum support line symbol placement based on _visibleParts_ as is provided for area placement.

Another limiting factor is that the portrayal doesn't know the length of the visible portion(s) of the curve, so it can't dynamically add/remove labels based on the length.

![image](https://user-images.githubusercontent.com/62906211/181310198-f39ef241-ea86-4b85-ace1-42d0eb3e3a5a.png)


See also S-52 portrayal bulletin PB6:

> ​​​​​​​PB6 - S-52-CPB-No 8: Equal placement of depth contour labels (CSMWG18 Action 16)
> Depth contour lines are often coded in segments of equal status with varying run lengths. Short contour segments are sometimes not optimal for the presentation of contour labels if the generic rules of DPCNT03 are too strictly applied. Therefore, the interpretation of DEPCNT03 rules to display depth contour labels should be interpreted in a way, that it results in an equal spaced placement of the labels with a distance which is independent from the fraction of the contour into segments and fits well to the selected display scale.​​​​​​​

and an implementation note from S-100WG3-8.5 (as noted above, this has been changed in the current portrayal):
![image](https://user-images.githubusercontent.com/62906211/181309058-e43b8b6b-716b-4506-a751-fd976d2b724b.png)
![image](https://user-images.githubusercontent.com/62906211/181309225-a4a5e76a-aabd-4378-ab78-3911762a0ed6.png)

**Comment by alvarosanuy** [comment]
The problem in the screenshot is that, either due to lack of good S-52 guidance or due to bad implementation by OEMs, labels where added on each geometric Edge and not on the overarching DEPCNT feature.
If this has now been solved in S-101 (by directing adding a label at the center of the feature) then we should now focus on making sure that something is displayed when the 'center' of the depth contour is not on the ECDIS display.
As suggested by Dave, this can be done by using the visibleParts concept (similarly to Surfaces) or maybe by instructing the display of labels every 120 mm (?) on the screen.

**Comment by DavidGrant-NIWC** [comment]
> As suggested by Dave, this can be done by using the visibleParts concept [...]

Will require changes to S-100 Part 9 / 9a. _visibleParts_ is not currently an option for lines. We'll generate a proposal for the upcoming WG.

**Comment by DavidGrant-NIWC** [comment]
> or maybe by instructing the display of labels every 120 mm (?) on the screen.

* Based on this suggestion we've generated a prototype portrayal which places labels at repeating 120mm intervals,
  * Each label is centered on an interval.
* Curves shorter than 60mm will not be labeled
  * Seems to help with display clutter.
  * Zooming in will increase the number of labels as curves get longer than 60mm.
  * Zooming out will decrease the number of labels as curves get shorter than 60mm.
* Due to the way the safety contour is constructed it is impossible to guarantee that it will not end up with many labels bunched together.
  * We tried to improve the presentation by only labeling each curve segment once
    * Previously, the depth areas on both sides of the safety contour would generate a label.
* This implementation requires a small change to S-100
  * Need to be able to specify PortrayalCRS for the LineSymbol command.
  * The change lets us draw upright labels
    * Otherwise the labels would be rotated so that they are oriented with the curve.
  * I'll generate a change proposal for S-100WG7

![ShoreECDIS 2022-09-28T221707Z](https://user-images.githubusercontent.com/62906211/192898634-a331b9c7-b7e0-40ea-a3f2-5eaaec09eb4c.png)

|1:12k|1:4k|
|:---:|:---:|
|![ShoreECDIS 2022-09-28T213719Z](https://user-images.githubusercontent.com/62906211/192893537-4df4b3f1-e3c5-4f93-be7c-d0ecb3352dfb.png)|![ShoreECDIS 2022-09-28T213957Z](https://user-images.githubusercontent.com/62906211/192893675-6f26a2bc-6324-4753-b1b7-25ef99d0f4f2.png)|

|1:45k|1:12k|
|:---:|:---:|
|![ShoreECDIS 2022-09-28T214522Z](https://user-images.githubusercontent.com/62906211/192894492-85c81f51-80c9-440f-812f-8da0838e2932.png)|![ShoreECDIS 2022-09-28T214656Z](https://user-images.githubusercontent.com/62906211/192894595-76a267bd-4f16-4367-9e40-6588cec674ff.png)|
|![ShoreECDIS 2022-09-28T221226Z](https://user-images.githubusercontent.com/62906211/192898073-58660cef-08ae-4563-b014-ccab54d02d6b.png)|![ShoreECDIS 2022-09-28T221236Z](https://user-images.githubusercontent.com/62906211/192898103-c0050954-ddd1-4814-b719-1bd88a378b6c.png)|

**Comment by alvarosanuy** [comment]
@DavidGrant-NIWC - Thanks for prototyping the idea. I think it looks promising.
My only concern is about leaving some small isolated shoals/deeps without a contour value. I understand that the reason is that the contour's total length is =< 120mm on the screen but, is there anyway to 'force' the display of a CV per contour when their total length =< 120 mm? 
Encoding at least one CV per depth contour is a recognised paper chart (S-4) practice. I'm sure there will be valid points against and in favour of replicating this in ECDIS (considering that mariners have other tools available such us pick report and alarms) but I think it's important to keep this in mind when discussing this topic and coming up with decisions.

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 12th January 2023**

1. @DavidGrant-NIWC confirmed that the paper was presented at S100WG7 and that although the CRS proposal was approved, the use of the 'Visible Parts' concept for Curves was not.

2. The subWG decided to go ahead with the implementation tested above by NIWC (equidistant labels every 120mm with the first label starting 20-30mm from the beginning of the Curve). NIWC proposed to delay implementation to PC 1.2.0 to wait for the official publication of the CRS change in the corresponding S100 document. This was supported by the subWG.

**Comment by DavidGrant-NIWC** [comment]
Use of 'Visible Parts' concept is approved for S-100 edition 5.1:
![image](https://user-images.githubusercontent.com/62906211/233125691-c3b8adaf-631d-4b1e-95f3-fc8535d91884.png)

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 11/5/23**

- Await the publication and endorsement of S100 5.1.0 schemas (to be approved at HSSC15 in June 2023) and apply changes to PC 1.2.0.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 17/10/23**

- Await the endorsement and release of S100 5.1.0 schemas (expected at S100WG8 - November 2023). 

- [ ] **NIWC** apply changes to PC 1.2.0 and update this issue when done.

**Comment by DavidGrant-NIWC** [comment]
Implemented via [PC 228](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/228)

Sample using a test dataset:

|1:22k (centered on each visible portion)|1:45k (centered on single visible portion)|
|:---:|:---:|
|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/53e7e88c-9887-4240-8e9a-8c9a4504396f)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/9129eed6-f72d-469c-a508-f5bd2cefdaac)

Mostly off screen:
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/e950e53f-4dd8-4381-81d1-d592c8581c12)
